/**
 * Authored-node snapshots of bundled workflows. GENERATED by scripts/generate-process-view-snapshot.ts
 * from workflows/production/flows/ — do not edit by hand; rerun `npm run prototype:snapshot`.
 * Prototype fixture data for the aggregated process view; not a runtime contract.
 */
import type { AuthoredNode } from "../model";

/** Quick Task — 23 authored nodes, workflow version 4.6.0. */
export const QUICK_TASK_AUTHORED: AuthoredNode[] = [
  {
    id: "start",
    type: "start",
    summary: "",
    connections: {
      default: "get-task",
    },
    progressNodeId: "scope",
  },
  {
    id: "get-task",
    type: "agent-directive",
    summary: "Establish the complete task contract from the triggering conversation.",
    connections: {
      success: "create-plan",
    },
    connectionLabels: {
      success: "task contract written",
    },
    inputs: ["task_file", "execution_file", "operating_mode", "progress_scope_outcome"],
    progressNodeId: "scope",
  },
  {
    id: "create-plan",
    type: "agent-directive",
    summary: "Read the complete task contract from {{get-task.task_file}}.",
    connections: {
      success: "plan-review",
    },
    connectionLabels: {
      success: "plan published",
    },
    inputs: ["current_plan_file", "progress_plan_outcome", "total_steps"],
    progressNodeId: "plan",
  },
  {
    id: "plan-review",
    type: "agent-directive",
    summary: "Obtain an independent reviewer through an available subagent or child workflow.",
    connections: {
      success: "check-plan-review-clean",
    },
    inputs: ["review_file", "issues_count", "progress_plan_outcome"],
    progressNodeId: "plan-review",
  },
  {
    id: "check-plan-review-clean",
    type: "condition",
    summary: "",
    connections: {
      true: "route-operating-mode-plan-approval",
      false: "repair-plan",
    },
    connectionLabels: {
      true: "no blocking findings",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "plan-review.issues_count",
      },
      right: 0,
    },
    progressNodeId: "plan-review",
  },
  {
    id: "repair-plan",
    type: "agent-directive",
    summary:
      "Read the complete current plan {{current_plan_file}}, its independent report {{plan-review.review_file}}, and the task contract {{get-task.task_file}}.",
    connections: {
      success: "plan-review",
    },
    connectionLabels: {
      success: {
        label: "review found issues",
        cycle: {
          cause:
            "The reviewer recorded at least one blocking finding, so a corrected plan iteration is created.",
          exit: "A review with zero blocking findings.",
        },
      },
    },
    inputs: ["current_plan_file", "progress_plan_outcome", "total_steps"],
    progressNodeId: "plan-review",
  },
  {
    id: "present-plan",
    type: "agent-directive",
    summary:
      "Read and present the complete independently reviewed plan {{current_plan_file}} with its clean review {{plan-review.review_file}} and ask for explicit approval.",
    connections: {
      success: "check-plan-approved",
    },
    inputs: ["approval", "decision_file", "progress_plan_outcome"],
    progressNodeId: "plan-approval",
  },
  {
    id: "check-plan-approved",
    type: "condition",
    summary: "",
    connections: {
      true: "check-steps-remaining",
      false: "revise-plan",
    },
    connectionLabels: {
      true: "approved, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "present-plan.approval",
      },
      right: "yes",
    },
    progressNodeId: "plan-approval",
  },
  {
    id: "revise-plan",
    type: "agent-directive",
    summary: "Publish the next immutable plan iteration from whichever basis applies to this run.",
    connections: {
      success: "plan-review",
    },
    connectionLabels: {
      success: {
        label: "user asked for changes",
        cycle: {
          cause:
            "The user rejected the plan or a replan was triggered during execution; a revised plan goes back through review.",
          exit: "The user approves, or the run is autonomous.",
        },
      },
    },
    inputs: ["current_plan_file", "progress_plan_outcome", "total_steps"],
    progressNodeId: "plan-approval",
  },
  {
    id: "check-steps-remaining",
    type: "condition",
    summary: "",
    connections: {
      true: "execute-step",
      false: "final-review",
    },
    connectionLabels: {
      false: "all units done",
    },
    condition: {
      operator: "lt",
      left: {
        contextPath: "current_step",
      },
      right: {
        contextPath: "total_steps",
      },
    },
    progressNodeId: "execute",
  },
  {
    id: "execute-step",
    type: "agent-directive",
    summary:
      "Read the approved plan {{current_plan_file}} and execute only its work unit at zero-based position {{current_step}}.",
    connections: {
      success: "close-completed-step",
    },
    inputs: ["progress_execution_outcome"],
    progressNodeId: "execute",
  },
  {
    id: "close-completed-step",
    type: "expression",
    summary: "",
    connections: {
      default: "check-steps-remaining",
    },
    connectionLabels: {
      default: {
        label: "next unit",
        cycle: {
          cause: "A unit was completed and units remain in the plan.",
          exit: "The plan cursor passes the last unit.",
        },
      },
    },
    expressions: ["current_step = current_step + 1"],
    progressNodeId: "execute",
  },
  {
    id: "final-review",
    type: "agent-directive",
    summary: "Obtain an independent reviewer through an available subagent or child workflow.",
    connections: {
      success: "check-review-clean",
    },
    inputs: ["review_file", "issues_count", "progress_review_outcome"],
    progressNodeId: "verify",
  },
  {
    id: "check-review-clean",
    type: "condition",
    summary: "",
    connections: {
      true: "route-operating-mode-result-presentation",
      false: "fix-issues",
    },
    connectionLabels: {
      true: "result accepted by review",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "final-review.issues_count",
      },
      right: 0,
    },
    progressNodeId: "verify",
  },
  {
    id: "route-operating-mode-result-presentation",
    type: "condition",
    summary: "",
    connections: {
      true: "present-autonomous-result",
      false: "present-to-user",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "operating_mode",
      },
      right: "autonomous",
    },
    progressNodeId: "deliver",
  },
  {
    id: "present-autonomous-result",
    type: "agent-directive",
    summary:
      "Read the task {{get-task.task_file}}, approved plan {{current_plan_file}}, accumulated evidence {{get-task.execution_file}}, latest clean result review {{fin…",
    connections: {
      success: "end",
    },
    inputs: ["progress_result_outcome"],
    progressNodeId: "deliver",
  },
  {
    id: "fix-issues",
    type: "agent-directive",
    summary: "Read the complete current result review {{final-review.review_file}}.",
    connections: {
      success: "final-review",
    },
    connectionLabels: {
      success: {
        label: "review found issues",
        cycle: {
          cause: "The final review recorded blocking findings, so the result is repaired.",
          exit: "A final review with zero findings.",
        },
      },
    },
    inputs: ["progress_review_outcome"],
    progressNodeId: "verify",
  },
  {
    id: "present-to-user",
    type: "agent-directive",
    summary:
      "Read the task {{get-task.task_file}}, approved plan {{current_plan_file}}, the plan decision record beside that plan, accumulated evidence {{get-task.executi…",
    connections: {
      success: "check-user-accepts",
    },
    inputs: ["decision", "decision_file", "progress_result_outcome"],
    progressNodeId: "deliver",
  },
  {
    id: "check-user-accepts",
    type: "condition",
    summary: "",
    connections: {
      true: "end",
      false: "rework",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "present-to-user.decision",
      },
      right: "accept",
    },
    progressNodeId: "deliver",
  },
  {
    id: "rework",
    type: "agent-directive",
    summary:
      "Read the exact user decision and feedback {{present-to-user.decision_file}}, task {{get-task.task_file}}, approved plan {{current_plan_file}}, and current cl…",
    connections: {
      success: "final-review",
    },
    connectionLabels: {
      success: {
        label: "user requested rework",
        cycle: {
          cause: "The user did not accept the result, so it is reworked and reviewed again.",
          exit: "The user accepts, or the run is autonomous.",
        },
      },
    },
    inputs: ["progress_result_outcome"],
    progressNodeId: "deliver",
  },
  {
    id: "end",
    type: "end",
    summary: "",
    connections: {},
    progressNodeId: "deliver",
  },
  {
    id: "route-operating-mode-plan-approval",
    type: "condition",
    summary: "",
    connections: {
      true: "check-steps-remaining",
      false: "present-plan",
    },
    connectionLabels: {
      true: "approved, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "operating_mode",
      },
      right: "autonomous",
    },
    progressNodeId: "plan-approval",
  },
  {
    id: "teleport-replan",
    type: "teleport",
    summary: "You jumped here because the approved plan no longer fits the real work.",
    connections: {
      success: "revise-plan",
    },
    inputs: ["progress_plan_outcome"],
    progressNodeId: "plan-approval",
  },
];

/** Software Development Flow — 130 authored nodes, workflow version 15.6.0. */
export const SDF_AUTHORED: AuthoredNode[] = [
  {
    id: "start",
    type: "start",
    summary: "",
    connections: {
      default: "capture-task-and-context",
    },
    progressNodeId: "intake",
  },
  {
    id: "end",
    type: "end",
    summary: "",
    connections: {},
    progressNodeId: "finalize",
  },
  {
    id: "capture-task-and-context",
    type: "agent-directive",
    summary: "Capture the user's development task and authority before repository mutation.",
    connections: {
      success: "materialize-development-standards",
    },
    inputs: [
      "workspace_path",
      "operating_mode",
      "visual_validation_preference",
      "progress_intake_outcome",
    ],
    progressNodeId: "intake",
  },
  {
    id: "materialize-development-standards",
    type: "materialize",
    summary: "",
    connections: {
      success: "route-operating-mode-requirements",
    },
    progressNodeId: "intake",
  },
  {
    id: "confirm-requirements",
    type: "agent-directive",
    summary:
      "Present the complete current requirements at {{workspace_path}}/task-requirements.md and ask whether they accurately capture the task, constraints, authority…",
    connections: {
      success: "route-requirements-approval",
    },
    inputs: ["requirements_approval", "user_feedback", "progress_intake_outcome"],
    progressNodeId: "intake",
  },
  {
    id: "route-requirements-approval",
    type: "condition",
    summary: "",
    connections: {
      true: "assess-project-health",
      false: "revise-requirements",
    },
    connectionLabels: {
      true: "requirements confirmed, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "confirm-requirements.requirements_approval",
      },
      right: "yes",
    },
    progressNodeId: "intake",
  },
  {
    id: "revise-requirements",
    type: "agent-directive",
    summary:
      "Use the verbatim feedback in {{workspace_path}}/requirements-feedback.md to update {{workspace_path}}/task-requirements.md.",
    connections: {
      success: "route-operating-mode-requirements",
    },
    connectionLabels: {
      success: {
        label: "user revised requirements",
        cycle: {
          cause:
            "The user rejected the requirements as captured, so they are revised and confirmed again.",
          exit: "The user approves, or the run is autonomous.",
        },
      },
    },
    inputs: ["progress_intake_outcome"],
    progressNodeId: "intake",
  },
  {
    id: "assess-project-health",
    type: "agent-directive",
    summary: "Before assessment, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-health-external",
    },
    inputs: ["health_outcome", "progress_intake_outcome"],
    progressNodeId: "health",
  },
  {
    id: "route-health-external",
    type: "condition",
    summary: "",
    connections: {
      true: "wait-for-health-state-change",
      false: "create-plan",
    },
    connectionLabels: {
      false: "baseline established",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "assess-project-health.health_outcome",
      },
      right: "external_blocker",
    },
    progressNodeId: "health",
  },
  {
    id: "wait-for-health-state-change",
    type: "agent-directive",
    summary: "Present the external blocker from {{workspace_path}}/project-health.md.",
    connections: {
      success: "route-health-retry",
    },
    inputs: ["blocker_decision", "progress_intake_outcome"],
    progressNodeId: "health",
  },
  {
    id: "route-health-retry",
    type: "condition",
    summary: "",
    connections: {
      true: "assess-project-health",
      false: "notify-workflow-stopped",
    },
    connectionLabels: {
      true: {
        label: "external blocker cleared",
        cycle: {
          cause:
            "The baseline failed on something outside the repository; the run waited for it to change.",
          exit: "The external state changed and the check is re-run, or the run stops.",
        },
      },
      false: "blocker did not clear",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "wait-for-health-state-change.blocker_decision",
      },
      right: "retry",
    },
    progressNodeId: "health",
  },
  {
    id: "create-plan",
    type: "agent-directive",
    summary: "Before planning, read `{{workspace_path}}/standards/planning.md`.",
    connections: {
      success: "review-plan",
    },
    inputs: ["progress_plan_outcome"],
    progressNodeId: "plan",
  },
  {
    id: "review-plan",
    type: "agent-directive",
    summary:
      "Before review, read `{{workspace_path}}/standards/planning.md` and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-plan-review-replan",
    },
    inputs: ["review_outcome", "progress_plan_outcome"],
    progressNodeId: "plan",
  },
  {
    id: "route-plan-review",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-plan",
      false: "route-plan-activation-mode",
    },
    connectionLabels: {
      false: "review clean",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-plan.review_outcome",
      },
      right: "repair",
    },
    progressNodeId: "plan",
  },
  {
    id: "repair-plan",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/planning.md` and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-plan-repair-outcome",
    },
    inputs: ["repair_outcome", "progress_plan_outcome"],
    progressNodeId: "plan",
  },
  {
    id: "approve-plan",
    type: "agent-directive",
    summary:
      "Present the complete independently reviewed current plan revision at {{workspace_path}}/plans/{{plan_revision}}/plan.md, including architecture, outcomes, de…",
    connections: {
      success: "route-plan-approval",
    },
    inputs: ["plan_approval", "user_feedback", "progress_plan_outcome"],
    progressNodeId: "plan-approval",
  },
  {
    id: "route-plan-approval",
    type: "condition",
    summary: "",
    connections: {
      true: "activate-reviewed-plan",
      false: "advance-plan-revision-after-rejection",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "approve-plan.plan_approval",
      },
      right: "yes",
    },
    progressNodeId: "plan-approval",
  },
  {
    id: "revise-plan-after-rejection",
    type: "agent-directive",
    summary: "Before this responsibility, read `{{workspace_path}}/standards/planning.md`.",
    connections: {
      success: "review-plan",
    },
    connectionLabels: {
      success: {
        label: "user rejected the plan",
        cycle: {
          cause: "The user asked for changes, so a new plan revision is written and reviewed.",
          exit: "The user approves, or the run is autonomous.",
        },
      },
    },
    inputs: ["progress_plan_outcome"],
    progressNodeId: "plan-approval",
  },
  {
    id: "initialize-implementation-iteration",
    type: "expression",
    summary: "",
    connections: {
      default: "prepare-plan-unit-implementation",
    },
    expressions: [
      "current_iteration = 1",
      "previous_iteration = 0",
      "product_review_iteration = 0",
    ],
    progressNodeId: "implement",
  },
  {
    id: "implement-plan-unit",
    type: "agent-directive",
    summary:
      "Before implementation, read `{{workspace_path}}/standards/engineering.md` and `{{workspace_path}}/standards/tests.md`.",
    connections: {
      success: "complete-plan-unit",
    },
    inputs: ["progress_implementation_outcome"],
    progressNodeId: "implement",
  },
  {
    id: "validate-cheap",
    type: "agent-directive",
    summary:
      "Before validation, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-cheap-validation",
    },
    inputs: ["issues_count", "progress_tests_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "route-cheap-validation",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-cheap-validation",
      false: "review-test-adequacy",
    },
    condition: {
      operator: "gt",
      left: {
        contextPath: "validate-cheap.issues_count",
      },
      right: 0,
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "repair-cheap-validation",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-cheap-repair-replan",
    },
    inputs: ["repair_outcome", "mutation_scope", "progress_tests_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "review-test-adequacy",
    type: "agent-directive",
    summary:
      "Before review, read `{{workspace_path}}/standards/tests.md` and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-test-adequacy-replan",
    },
    inputs: ["review_outcome", "progress_tests_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "route-test-adequacy",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-test-adequacy",
      false: "route-current-verification-only",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-test-adequacy.review_outcome",
      },
      right: "repair",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "repair-test-adequacy",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/tests.md` and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-test-repair-outcome",
    },
    inputs: ["repair_outcome", "mutation_scope", "progress_tests_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "review-architecture",
    type: "agent-directive",
    summary:
      "Before review, read `{{workspace_path}}/standards/engineering.md` and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-architecture-replan",
    },
    inputs: ["review_outcome", "progress_review_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "route-architecture-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-architecture-review",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-architecture.review_outcome",
      },
      right: "replan",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-architecture-review",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-architecture",
      false: "mark-product-review-current",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-architecture.review_outcome",
      },
      right: "repair",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "repair-architecture",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/engineering.md` and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-architecture-repair-outcome",
    },
    inputs: ["repair_outcome", "mutation_scope", "progress_review_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "approve-current-unit-closure",
    type: "agent-directive",
    summary:
      "Read the complete current unit and exactly one route-current replan source, then decide whether unit {{current_step_index}} may close for a material plan rev…",
    connections: {
      success: "route-current-unit-closure",
    },
    inputs: ["closure_decision", "progress_plan_outcome"],
    progressNodeId: "replan",
  },
  {
    id: "route-current-unit-closure",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "notify-workflow-stopped",
    },
    connectionLabels: {
      false: "closure not approved",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "approve-current-unit-closure.closure_decision",
      },
      right: "approved",
    },
    progressNodeId: "replan",
  },
  {
    id: "revise-plan-for-replan",
    type: "agent-directive",
    summary: "Before revising, read `{{workspace_path}}/standards/planning.md`.",
    connections: {
      success: "review-plan",
    },
    connectionLabels: {
      success: {
        label: "revised plan goes to review",
        cycle: {
          cause: "New facts, missed scope, or an upstream defect invalidated the remaining plan.",
          exit: "The revised plan passes review and is activated.",
        },
      },
    },
    inputs: ["progress_plan_outcome"],
    progressNodeId: "replan",
  },
  {
    id: "validate-runtime",
    type: "agent-directive",
    summary: "Before runtime validation, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-runtime-external",
    },
    inputs: ["validation_outcome", "progress_review_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "route-runtime-external",
    type: "condition",
    summary: "",
    connections: {
      true: "wait-for-runtime-state-change",
      false: "route-runtime-repository",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "validate-runtime.validation_outcome",
      },
      right: "external_blocker",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-runtime-repository",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-runtime",
      false: "validate-expensive",
    },
    connectionLabels: {
      false: "all gates green",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "validate-runtime.validation_outcome",
      },
      right: "repository_failure",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "repair-runtime",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-runtime-repair-replan",
    },
    inputs: ["repair_outcome", "mutation_scope", "progress_review_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "wait-for-runtime-state-change",
    type: "agent-directive",
    summary: "Present the concrete external blocker from the current runtime-validation report.",
    connections: {
      success: "route-runtime-retry",
    },
    inputs: ["blocker_decision", "progress_review_outcome"],
    progressNodeId: "unit-validation",
  },
  {
    id: "route-runtime-retry",
    type: "condition",
    summary: "",
    connections: {
      true: "validate-runtime",
      false: "notify-workflow-stopped",
    },
    connectionLabels: {
      true: {
        label: "retry runtime validation",
        cycle: {
          cause: "Runtime validation failed on something the repair can fix inside the gate.",
          exit: "Runtime validation passes, or the repair escalates.",
        },
      },
      false: "external blocker did not clear",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "wait-for-runtime-state-change.blocker_decision",
      },
      right: "retry",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "validate-expensive",
    type: "agent-directive",
    summary: "Before broad validation, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-expensive-external",
    },
    inputs: ["validation_outcome", "progress_review_outcome"],
    progressNodeId: "broad-validation",
  },
  {
    id: "route-expensive-external",
    type: "condition",
    summary: "",
    connections: {
      true: "wait-for-expensive-state-change",
      false: "route-expensive-repository",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "validate-expensive.validation_outcome",
      },
      right: "external_blocker",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "route-expensive-repository",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-expensive",
      false: "update-unit-documentation",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "validate-expensive.validation_outcome",
      },
      right: "repository_failure",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "update-unit-documentation",
    type: "agent-directive",
    summary:
      "Before changing permanent documentation, read `{{workspace_path}}/standards/documentation.md`.",
    connections: {
      success: "route-unit-documentation-replan",
    },
    inputs: ["documentation_outcome", "progress_review_outcome"],
    progressNodeId: "broad-validation",
  },
  {
    id: "route-unit-documentation-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-unit-documentation-product-repair",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "update-unit-documentation.documentation_outcome",
      },
      right: "replan",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "route-unit-documentation-product-repair",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-evidence-iteration",
      false: "review-unit-completeness",
    },
    connectionLabels: {
      true: {
        label: "documentation exposed a product defect",
        cycle: {
          cause:
            "Writing the documentation revealed behavior that must change before the docs can be true.",
          exit: "Documentation describes the current behavior truthfully.",
        },
      },
      false: "evidence and docs current",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "update-unit-documentation.documentation_outcome",
      },
      right: "product_repair",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "repair-expensive",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-expensive-repair-replan",
    },
    inputs: ["repair_outcome", "mutation_scope", "progress_review_outcome"],
    progressNodeId: "broad-validation",
  },
  {
    id: "wait-for-expensive-state-change",
    type: "agent-directive",
    summary: "Present the concrete external blocker from the current expensive-validation report.",
    connections: {
      success: "route-expensive-retry",
    },
    inputs: ["blocker_decision", "progress_review_outcome"],
    progressNodeId: "broad-validation",
  },
  {
    id: "route-expensive-retry",
    type: "condition",
    summary: "",
    connections: {
      true: "validate-expensive",
      false: "notify-workflow-stopped",
    },
    connectionLabels: {
      true: {
        label: "retry expensive validation",
        cycle: {
          cause: "Expensive validation failed and the repair stayed local to the gate.",
          exit: "Expensive validation passes.",
        },
      },
      false: "external blocker did not clear",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "wait-for-expensive-state-change.blocker_decision",
      },
      right: "retry",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "review-plan-unit-with-user",
    type: "agent-directive",
    summary:
      "Read the complete current unit at {{workspace_path}}/plans/{{plan_revision}}/plan.md, then present its accepted outcome and exact current evidence for user d…",
    connections: {
      success: "route-plan-unit-user-review",
    },
    inputs: ["acceptance_decision", "user_feedback", "progress_review_outcome"],
    progressNodeId: "user-review",
  },
  {
    id: "route-plan-unit-user-review",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-user-feedback",
      false: "route-checkpoint-authority",
    },
    connectionLabels: {
      false: "accepted, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-plan-unit-with-user.acceptance_decision",
      },
      right: "rejected",
    },
    progressNodeId: "user-review",
  },
  {
    id: "repair-user-feedback",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, and `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-user-feedback-resolution",
    },
    inputs: ["resolution", "progress_implementation_outcome"],
    progressNodeId: "user-review",
  },
  {
    id: "route-vcs-authority",
    type: "condition",
    summary: "",
    connections: {
      true: "finalize-feature",
      false: "notify-workflow-complete",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "vcs_commits_authorized",
      },
      right: true,
    },
    progressNodeId: "finalize",
  },
  {
    id: "route-finalization-success",
    type: "condition",
    summary: "",
    connections: {
      true: "notify-workflow-complete",
      false: "route-finalization-repository",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "finalize-feature.finalization_outcome",
      },
      right: "pass",
    },
    progressNodeId: "finalize",
  },
  {
    id: "resolve-finalization-blocker",
    type: "agent-directive",
    summary:
      "Present the concrete external finalization blocker from {{workspace_path}}/finalization.md.",
    connections: {
      success: "route-finalization-retry",
    },
    inputs: ["blocker_decision", "progress_finalize_outcome"],
    progressNodeId: "finalize",
  },
  {
    id: "route-finalization-retry",
    type: "condition",
    summary: "",
    connections: {
      true: "finalize-feature",
      false: "route-finalization-skip",
    },
    connectionLabels: {
      true: {
        label: "retry finalization",
        cycle: {
          cause: "Finalization failed on something retryable.",
          exit: "Finalization completes.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "resolve-finalization-blocker.blocker_decision",
      },
      right: "retry",
    },
    progressNodeId: "finalize",
  },
  {
    id: "route-finalization-skip",
    type: "condition",
    summary: "",
    connections: {
      true: "notify-workflow-complete",
      false: "notify-workflow-stopped",
    },
    connectionLabels: {
      false: "finalization could not complete",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "resolve-finalization-blocker.blocker_decision",
      },
      right: "skip",
    },
    progressNodeId: "finalize",
  },
  {
    id: "route-plan-complete",
    type: "condition",
    summary: "",
    connections: {
      true: "validate-feature-wide",
      false: "advance-plan-unit",
    },
    connectionLabels: {
      true: "last unit closed",
    },
    condition: {
      operator: "gte",
      left: {
        contextPath: "current_step_index",
      },
      right: {
        contextPath: "total_steps",
      },
    },
    progressNodeId: "checkpoint",
  },
  {
    id: "advance-plan-unit",
    type: "expression",
    summary: "",
    connections: {
      default: "prepare-plan-unit-implementation",
    },
    connectionLabels: {
      default: {
        label: "next unit",
        cycle: {
          cause: "A unit was closed and units remain in the plan.",
          exit: "The plan cursor passes the last unit.",
        },
      },
    },
    expressions: [
      "current_step_index = current_step_index + 1",
      "current_iteration = 1",
      "previous_iteration = 0",
      "product_review_iteration = 0",
    ],
    progressNodeId: "checkpoint",
  },
  {
    id: "validate-feature-wide",
    type: "agent-directive",
    summary: "Before this responsibility, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-feature-external",
    },
    inputs: ["validation_outcome", "progress_finalize_outcome"],
    progressNodeId: "feature-validation",
  },
  {
    id: "route-feature-external",
    type: "condition",
    summary: "",
    connections: {
      true: "wait-for-feature-state-change",
      false: "route-feature-repository",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "validate-feature-wide.validation_outcome",
      },
      right: "external_blocker",
    },
    progressNodeId: "feature-validation",
  },
  {
    id: "route-feature-repository",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-feature-validation",
      false: "review-final-semantics",
    },
    connectionLabels: {
      false: "feature evidence green",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "validate-feature-wide.validation_outcome",
      },
      right: "repository_failure",
    },
    progressNodeId: "feature-validation",
  },
  {
    id: "repair-feature-validation",
    type: "agent-directive",
    summary: "Before repair, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-feature-repair-replan",
    },
    inputs: ["repair_outcome", "progress_finalize_outcome"],
    progressNodeId: "feature-validation",
  },
  {
    id: "wait-for-feature-state-change",
    type: "agent-directive",
    summary: "Present the concrete external blocker in {{workspace_path}}/feature-validation.md.",
    connections: {
      success: "route-feature-retry",
    },
    inputs: ["blocker_decision", "progress_finalize_outcome"],
    progressNodeId: "feature-validation",
  },
  {
    id: "route-feature-retry",
    type: "condition",
    summary: "",
    connections: {
      true: "validate-feature-wide",
      false: "notify-workflow-stopped",
    },
    connectionLabels: {
      true: {
        label: "retry feature-wide validation",
        cycle: {
          cause: "Feature-wide validation failed and the repair stayed local.",
          exit: "Feature-wide validation passes.",
        },
      },
      false: "external blocker did not clear",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "wait-for-feature-state-change.blocker_decision",
      },
      right: "retry",
    },
    progressNodeId: "feature-validation",
  },
  {
    id: "review-final-semantics",
    type: "agent-directive",
    summary:
      "Before independent final review, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, `{{workspace_path}}/standards/d…",
    connections: {
      success: "route-final-review-replan",
    },
    inputs: ["review_outcome", "gaps_count", "review_file", "progress_finalize_outcome"],
    progressNodeId: "final-review",
  },
  {
    id: "route-final-semantic-review",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-final-semantics",
      false: "create-final-report",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-final-semantics.review_outcome",
      },
      right: "repair",
    },
    progressNodeId: "final-review",
  },
  {
    id: "repair-final-semantics",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/documentation.md` and `{{workspace_path}}/standards/review.md`, the exact `{{review-final-semantics.review_…",
    connections: {
      success: "route-final-repair-replan",
    },
    inputs: ["repair_outcome", "result_file", "progress_finalize_outcome"],
    progressNodeId: "final-review",
  },
  {
    id: "report-and-accept-feature",
    type: "agent-directive",
    summary:
      "Read the current final report at {{workspace_path}}/final-report.md and present its exact current repository result for an interactive user decision.",
    connections: {
      success: "route-feature-acceptance",
    },
    inputs: ["feature_decision", "user_feedback", "progress_finalize_outcome"],
    progressNodeId: "final-review",
  },
  {
    id: "route-feature-acceptance",
    type: "condition",
    summary: "",
    connections: {
      true: "route-vcs-authority",
      false: "advance-plan-revision-after-feedback",
    },
    connectionLabels: {
      true: "accepted, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "report-and-accept-feature.feature_decision",
      },
      right: "accepted",
    },
    progressNodeId: "final-review",
  },
  {
    id: "revise-plan-after-feedback",
    type: "agent-directive",
    summary: "Before this responsibility, read `{{workspace_path}}/standards/planning.md`.",
    connections: {
      success: "review-plan",
    },
    connectionLabels: {
      success: {
        label: "user feedback reopens the plan",
        cycle: {
          cause: "The user did not accept the feature; a revised plan goes back through review.",
          exit: "The user accepts the feature.",
        },
      },
    },
    inputs: ["progress_plan_outcome"],
    progressNodeId: "final-review",
  },
  {
    id: "end-aborted",
    type: "end",
    summary: "",
    connections: {},
    progressNodeId: "stopped",
  },
  {
    id: "route-user-feedback-resolution",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: "feedback invalidates the plan",
      false: {
        label: "user feedback needs repair",
        cycle: {
          cause: "The user asked for changes to the unit.",
          exit: "The user accepts the unit.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-user-feedback.resolution",
      },
      right: "replan",
    },
    progressNodeId: "user-review",
  },
  {
    id: "finalize-feature",
    type: "agent-directive",
    summary:
      "Within the already authorized project-native commit boundary, reconcile only remaining task-owned changes created after or deliberately excluded from the las…",
    connections: {
      success: "route-finalization-success",
    },
    inputs: ["finalization_outcome", "progress_finalize_outcome"],
    progressNodeId: "finalize",
  },
  {
    id: "route-finalization-repository",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-finalization-repository",
      false: "resolve-finalization-blocker",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "finalize-feature.finalization_outcome",
      },
      right: "repository_failure",
    },
    progressNodeId: "finalize",
  },
  {
    id: "repair-finalization-repository",
    type: "agent-directive",
    summary: "Before repair, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-finalization-repair-replan",
    },
    inputs: ["repair_outcome", "progress_finalize_outcome"],
    progressNodeId: "finalize",
  },
  {
    id: "route-checkpoint-authority",
    type: "condition",
    summary: "",
    connections: {
      true: "checkpoint-plan-unit",
      false: "route-plan-complete",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "vcs_commits_authorized",
      },
      right: true,
    },
    progressNodeId: "checkpoint",
  },
  {
    id: "checkpoint-plan-unit",
    type: "agent-directive",
    summary:
      "Create the already authorized project-native commit for accepted unit {{current_step_index}} after its current validation and conditional user acceptance.",
    connections: {
      success: "route-plan-complete",
    },
    inputs: ["progress_checkpoint_outcome"],
    progressNodeId: "checkpoint",
  },
  {
    id: "route-operating-mode-requirements",
    type: "condition",
    summary: "",
    connections: {
      true: "assess-project-health",
      false: "confirm-requirements",
    },
    connectionLabels: {
      true: "requirements confirmed, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "operating_mode",
      },
      right: "autonomous",
    },
    progressNodeId: "intake",
  },
  {
    id: "review-unit-completeness",
    type: "agent-directive",
    summary:
      "Before independent review, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, `{{workspace_path}}/standards/documen…",
    connections: {
      success: "route-completeness-review-replan",
    },
    inputs: ["review_outcome", "progress_review_outcome", "progress_checkpoint_outcome"],
    progressNodeId: "completeness",
  },
  {
    id: "route-unit-completeness",
    type: "condition",
    summary: "",
    connections: {
      true: "repair-unit-completeness",
      false: "route-unit-html-report",
    },
    connectionLabels: {
      false: "zero findings",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-unit-completeness.review_outcome",
      },
      right: "repair",
    },
    progressNodeId: "completeness",
  },
  {
    id: "repair-unit-completeness",
    type: "agent-directive",
    summary:
      "Before repair, read `{{workspace_path}}/standards/engineering.md`, `{{workspace_path}}/standards/tests.md`, `{{workspace_path}}/standards/documentation.md`, …",
    connections: {
      success: "route-completeness-repair-outcome",
    },
    inputs: ["repair_outcome", "mutation_scope", "progress_review_outcome"],
    progressNodeId: "completeness",
  },
  {
    id: "teleport-replan",
    type: "teleport",
    summary: "You jumped here because the current plan no longer fits reality.",
    connections: {
      success: "advance-plan-revision-for-teleport",
    },
    inputs: ["replan_rationale", "progress_plan_outcome"],
    progressNodeId: "replan",
  },
  {
    id: "advance-plan-revision-for-teleport",
    type: "expression",
    summary: "",
    connections: {
      default: "revise-plan-for-teleport",
    },
    expressions: ["previous_plan_revision = plan_revision", "plan_revision = plan_revision + 1"],
    progressNodeId: "replan",
  },
  {
    id: "revise-plan-for-teleport",
    type: "agent-directive",
    summary: "Before this responsibility, read `{{workspace_path}}/standards/planning.md`.",
    connections: {
      success: "review-plan",
    },
    connectionLabels: {
      success: {
        label: "revised plan goes to review",
        cycle: {
          cause: "New facts, missed scope, or an upstream defect invalidated the remaining plan.",
          exit: "The revised plan passes review and is activated.",
        },
      },
    },
    inputs: ["progress_plan_outcome"],
    progressNodeId: "replan",
  },
  {
    id: "route-test-adequacy-reach",
    type: "condition",
    summary: "",
    connections: {
      true: "mark-verification-only-iteration",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
      false: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-test-adequacy.mutation_scope",
      },
      right: "verification_only",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-architecture-reach",
    type: "condition",
    summary: "",
    connections: {
      true: "review-architecture",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: {
        label: "architecture review again",
        cycle: {
          cause:
            "The architecture repair stayed within the gate's reach, so the review is repeated.",
          exit: "The architecture review passes.",
        },
      },
      false: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-architecture.mutation_scope",
      },
      right: "gate_local",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-unit-completeness-reach",
    type: "condition",
    summary: "",
    connections: {
      true: "mark-verification-only-iteration",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: {
        label: "product defect found",
        cycle: {
          cause: "The completeness review found a defect that only a product change can resolve.",
          exit: "A completeness review with zero findings.",
        },
      },
      false: {
        label: "product defect found",
        cycle: {
          cause: "The completeness review found a defect that only a product change can resolve.",
          exit: "A completeness review with zero findings.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-unit-completeness.mutation_scope",
      },
      right: "verification_only",
    },
    progressNodeId: "completeness",
  },
  {
    id: "advance-evidence-iteration",
    type: "expression",
    summary: "",
    connections: {
      default: "complete-plan-unit",
    },
    connectionLabels: {
      default: {
        label: "next evidence iteration",
        cycle: {
          cause:
            "A repair reached product behaviour, so the unit is closed again with fresh evidence.",
          exit: "The unit closes with evidence that no later repair invalidated.",
        },
      },
    },
    expressions: [
      "previous_iteration = current_iteration",
      "current_iteration = current_iteration + 1",
    ],
    progressNodeId: "implement",
  },
  {
    id: "advance-plan-revision-after-rejection",
    type: "expression",
    summary: "",
    connections: {
      default: "revise-plan-after-rejection",
    },
    expressions: ["previous_plan_revision = plan_revision", "plan_revision = plan_revision + 1"],
    progressNodeId: "plan-approval",
  },
  {
    id: "advance-plan-revision-for-replan",
    type: "expression",
    summary: "",
    connections: {
      default: "revise-plan-for-replan",
    },
    expressions: ["previous_plan_revision = plan_revision", "plan_revision = plan_revision + 1"],
    progressNodeId: "replan",
  },
  {
    id: "advance-plan-revision-after-feedback",
    type: "expression",
    summary: "",
    connections: {
      default: "revise-plan-after-feedback",
    },
    expressions: ["previous_plan_revision = plan_revision", "plan_revision = plan_revision + 1"],
    progressNodeId: "final-review",
  },
  {
    id: "mark-current-evidence-iteration",
    type: "expression",
    summary: "",
    connections: {
      default: "review-unit-completeness",
    },
    connectionLabels: {
      default: {
        label: "evidence recorded, back to completeness review",
        cycle: {
          cause:
            "The unit's evidence iteration was recorded, so the completeness review runs again on it.",
          exit: "The completeness review accepts the unit.",
        },
      },
    },
    expressions: ["previous_iteration = current_iteration"],
    progressNodeId: "implement",
  },
  {
    id: "mark-verification-only-iteration",
    type: "expression",
    summary: "",
    connections: {
      default: "validate-cheap",
    },
    connectionLabels: {
      default: {
        label: "verification-only iteration",
        cycle: {
          cause:
            "A repair did not touch product behaviour, so validation runs again without re-implementing the unit.",
          exit: "Validation passes on the unchanged implementation.",
        },
      },
    },
    expressions: ["previous_iteration = current_iteration"],
    progressNodeId: "implement",
  },
  {
    id: "route-plan-review-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "route-plan-review",
    },
    connectionLabels: {
      true: "plan itself is wrong",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-plan.review_outcome",
      },
      right: "replan",
    },
    progressNodeId: "plan",
  },
  {
    id: "route-plan-repair-outcome",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "review-plan",
    },
    connectionLabels: {
      true: "plan itself is wrong",
      false: {
        label: "review found issues",
        cycle: {
          cause:
            "The independent reviewer recorded blocking findings, so the plan is repaired and reviewed again.",
          exit: "A review with zero blocking findings.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-plan.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "plan",
  },
  {
    id: "route-test-adequacy-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-test-adequacy",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-test-adequacy.review_outcome",
      },
      right: "replan",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-current-verification-only",
    type: "condition",
    summary: "",
    connections: {
      true: "validate-runtime",
      false: "review-architecture",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "product_review_iteration",
      },
      right: {
        contextPath: "current_iteration",
      },
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-test-repair-outcome",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-test-adequacy-reach",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-test-adequacy.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-architecture-repair-outcome",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-architecture-reach",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-architecture.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-completeness-review-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-unit-completeness",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-unit-completeness.review_outcome",
      },
      right: "replan",
    },
    progressNodeId: "completeness",
  },
  {
    id: "route-completeness-repair-outcome",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-completeness-repair-gate-local",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-unit-completeness.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "completeness",
  },
  {
    id: "route-completeness-repair-gate-local",
    type: "condition",
    summary: "",
    connections: {
      true: "mark-current-evidence-iteration",
      false: "route-unit-completeness-reach",
    },
    connectionLabels: {
      true: {
        label: "product defect found",
        cycle: {
          cause: "The completeness review found a defect that only a product change can resolve.",
          exit: "A completeness review with zero findings.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-unit-completeness.mutation_scope",
      },
      right: "gate_local",
    },
    progressNodeId: "completeness",
  },
  {
    id: "route-final-review-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "route-final-semantic-review",
    },
    connectionLabels: {
      true: "executable defect found",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "review-final-semantics.review_outcome",
      },
      right: "replan",
    },
    progressNodeId: "final-review",
  },
  {
    id: "route-final-repair-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "validate-feature-wide",
    },
    connectionLabels: {
      true: "executable defect found",
      false: {
        label: "gate-local repair",
        cycle: {
          cause:
            "The final review found a non-executable correction, so feature validation is re-established after it.",
          exit: "A final review with zero gaps.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-final-semantics.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "final-review",
  },
  {
    id: "route-cheap-repair-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-cheap-repair-scope",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-cheap-validation.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-cheap-repair-scope",
    type: "condition",
    summary: "",
    connections: {
      true: "mark-verification-only-iteration",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
      false: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-cheap-validation.mutation_scope",
      },
      right: "verification_only",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-runtime-repair-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-runtime-repair-scope",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-runtime.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-runtime-repair-scope",
    type: "condition",
    summary: "",
    connections: {
      true: "mark-verification-only-iteration",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
      false: {
        label: "product repair",
        cycle: {
          cause:
            "A gate found a defect whose repair reaches product code, so the unit is re-implemented and re-validated.",
          exit: "Every gate passes without a product change.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-runtime.mutation_scope",
      },
      right: "verification_only",
    },
    progressNodeId: "unit-validation",
  },
  {
    id: "route-expensive-repair-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "approve-current-unit-closure",
      false: "route-expensive-repair-scope",
    },
    connectionLabels: {
      true: "upstream cause",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-expensive.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "route-expensive-repair-scope",
    type: "condition",
    summary: "",
    connections: {
      true: "mark-verification-only-iteration",
      false: "advance-evidence-iteration",
    },
    connectionLabels: {
      true: {
        label: "documentation exposed a product defect",
        cycle: {
          cause:
            "Writing the documentation revealed behavior that must change before the docs can be true.",
          exit: "Documentation describes the current behavior truthfully.",
        },
      },
      false: {
        label: "documentation exposed a product defect",
        cycle: {
          cause:
            "Writing the documentation revealed behavior that must change before the docs can be true.",
          exit: "Documentation describes the current behavior truthfully.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-expensive.mutation_scope",
      },
      right: "verification_only",
    },
    progressNodeId: "broad-validation",
  },
  {
    id: "route-feature-repair-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "validate-feature-wide",
    },
    connectionLabels: {
      true: "repository failure needs a plan change",
      false: {
        label: "repaired, validate again",
        cycle: {
          cause: "A feature-wide repair did not need a replan, so validation runs again.",
          exit: "Feature-wide validation passes.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-feature-validation.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "feature-validation",
  },
  {
    id: "route-finalization-repair-replan",
    type: "condition",
    summary: "",
    connections: {
      true: "advance-plan-revision-for-replan",
      false: "finalize-feature",
    },
    connectionLabels: {
      true: {
        label: "finalization found an upstream cause",
        cycle: {
          cause: "Finalization exposed a defect whose cause lies upstream, so the plan is revised.",
          exit: "The revised plan is reviewed, activated, and finalization succeeds.",
        },
      },
      false: {
        label: "repaired, finalize again",
        cycle: {
          cause: "A finalization repair stayed local, so finalization is repeated.",
          exit: "Finalization completes.",
        },
      },
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "repair-finalization-repository.repair_outcome",
      },
      right: "replan",
    },
    progressNodeId: "finalize",
  },
  {
    id: "mark-product-review-current",
    type: "expression",
    summary: "",
    connections: {
      default: "validate-runtime",
    },
    expressions: ["product_review_iteration = current_iteration"],
    progressNodeId: "unit-validation",
  },
  {
    id: "prepare-plan-unit-implementation",
    type: "agent-directive",
    summary: "Before this responsibility, read `{{workspace_path}}/standards/planning.md`.",
    connections: {
      success: "route-implementation-preparation",
    },
    inputs: [
      "preparation_outcome",
      "visual_mode",
      "approval_required",
      "progress_implementation_outcome",
    ],
    progressNodeId: "implement",
  },
  {
    id: "route-implementation-preparation",
    type: "condition",
    summary: "",
    connections: {
      true: "implement-plan-unit",
      false: "approve-current-unit-closure",
    },
    connectionLabels: {
      false: "preparation found the plan invalid",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "prepare-plan-unit-implementation.preparation_outcome",
      },
      right: "ready",
    },
    progressNodeId: "implement",
  },
  {
    id: "complete-plan-unit",
    type: "agent-directive",
    summary:
      "Before producer completion, read `{{workspace_path}}/standards/engineering.md` and `{{workspace_path}}/standards/tests.md`.",
    connections: {
      success: "route-plan-unit-completion",
    },
    inputs: ["completion_outcome", "progress_implementation_outcome"],
    progressNodeId: "implement",
  },
  {
    id: "route-plan-unit-completion",
    type: "condition",
    summary: "",
    connections: {
      true: "validate-cheap",
      false: "approve-current-unit-closure",
    },
    connectionLabels: {
      true: "unit implemented",
      false: "preparation found the plan invalid",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "complete-plan-unit.completion_outcome",
      },
      right: "ready",
    },
    progressNodeId: "implement",
  },
  {
    id: "route-plan-activation-mode",
    type: "condition",
    summary: "",
    connections: {
      true: "notify-plan-approval",
      false: "activate-reviewed-plan",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "operating_mode",
      },
      right: "interactive",
    },
    progressNodeId: "plan-approval",
  },
  {
    id: "notify-plan-approval",
    type: "user-notification",
    summary:
      "📋 *Plan approval required*\n\nReviewed development plan revision {{plan_revision}} is ready for your decision.",
    connections: {
      default: "approve-plan",
    },
    progressNodeId: "plan-approval",
  },
  {
    id: "activate-reviewed-plan",
    type: "agent-directive",
    summary:
      "Activate the exact independently reviewed current plan revision at {{workspace_path}}/plans/{{plan_revision}}/plan.md without asking for or emitting approval.",
    connections: {
      success: "initialize-implementation-iteration",
    },
    connectionLabels: {
      success: "plan activated",
    },
    inputs: [
      "current_step_index",
      "total_steps",
      "vcs_commits_authorized",
      "progress_plan_outcome",
    ],
    progressNodeId: "plan-approval",
  },
  {
    id: "route-unit-html-report",
    type: "condition",
    summary: "",
    connections: {
      true: "create-and-upload-step-report",
      false: "route-unit-approval-required",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "prepare-plan-unit-implementation.visual_mode",
      },
      right: "html_report",
    },
    progressNodeId: "user-review",
  },
  {
    id: "create-and-upload-step-report",
    type: "agent-directive",
    summary:
      "Create the requested HTML report for unit {{current_step_index}} from the complete current unit, stabilized unit account, current validation evidence, accept…",
    connections: {
      success: "notify-report-ready",
    },
    inputs: ["report_url", "progress_review_outcome"],
    progressNodeId: "user-review",
  },
  {
    id: "notify-report-ready",
    type: "user-notification",
    summary:
      "🖼 *Visual report ready*\n\nPlan unit {{current_step_index}} report: {{create-and-upload-step-report.report_url}}",
    connections: {
      default: "route-unit-approval-required",
    },
    progressNodeId: "user-review",
  },
  {
    id: "route-unit-approval-required",
    type: "condition",
    summary: "",
    connections: {
      true: "notify-unit-approval",
      false: "route-checkpoint-authority",
    },
    connectionLabels: {
      false: "accepted, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "prepare-plan-unit-implementation.approval_required",
      },
      right: true,
    },
    progressNodeId: "user-review",
  },
  {
    id: "notify-unit-approval",
    type: "user-notification",
    summary:
      "👤 *Unit approval required*\n\nPlan unit {{current_step_index}} is ready and the workflow is waiting for your decision.",
    connections: {
      default: "review-plan-unit-with-user",
    },
    progressNodeId: "user-review",
  },
  {
    id: "notify-workflow-complete",
    type: "user-notification",
    summary:
      "✅ *Software Development Flow finished*\n\nThe workflow reached its normal terminal result.",
    connections: {
      default: "end",
    },
    progressNodeId: "finalize",
  },
  {
    id: "notify-workflow-stopped",
    type: "user-notification",
    summary:
      "⛔ *Software Development Flow stopped*\n\nThe workflow ended before normal completion.",
    connections: {
      default: "end-aborted",
    },
    progressNodeId: "stopped",
  },
  {
    id: "create-final-report",
    type: "agent-directive",
    summary: "Before reporting, read `{{workspace_path}}/standards/review.md`.",
    connections: {
      success: "route-final-acceptance-mode",
    },
    inputs: ["progress_finalize_outcome"],
    progressNodeId: "final-review",
  },
  {
    id: "route-final-acceptance-mode",
    type: "condition",
    summary: "",
    connections: {
      true: "notify-final-approval",
      false: "route-vcs-authority",
    },
    connectionLabels: {
      false: "accepted, or autonomous",
    },
    condition: {
      operator: "eq",
      left: {
        contextPath: "operating_mode",
      },
      right: "interactive",
    },
    progressNodeId: "final-review",
  },
  {
    id: "notify-final-approval",
    type: "user-notification",
    summary:
      "👤 *Final result approval required*\n\nThe complete Software Development Flow report is ready and the workflow is waiting for your decision.",
    connections: {
      default: "report-and-accept-feature",
    },
    progressNodeId: "final-review",
  },
];
