/**
 * Annotated workflow surfaces the derivation reads. GENERATED by
 * scripts/generate-process-view-snapshot.ts from workflows/production/flows/ — do not edit by hand;
 * rerun `npm run prototype:snapshot`.
 */
import type { AnnotatedWorkflow } from "../model";

export const QUICK_TASK_WORKFLOW: AnnotatedWorkflow = {
  slug: "quick-task",
  title: "Quick Task",
  goal: "Complete one bounded task through a reviewed plan, sequential verified work, independent result review, and truthful delivery.",
  version: "4.6.0",
  blocks: [
    {
      id: "scope",
      label: "Understand the task",
      summary:
        "Capture the goal, the observable result, scope, constraints, authority, and whether the run is autonomous or interactive. Nothing is planned yet.",
      outcome: "{{progress_scope_outcome}}",
      next_block: "plan",
    },
    {
      id: "plan",
      label: "Draft the plan",
      summary:
        "Write an ordered plan of 1–10 units, each with an action, an expected result, and a verification method. The plan is immutable once published.",
      outcome: "{{progress_plan_outcome}}",
      next_block: "plan-review",
    },
    {
      id: "plan-review",
      label: "Independent plan review",
      summary:
        "A reviewer who did not write the plan checks it against the task contract and records blocking findings. Findings send the plan back for repair until the review is clean.",
      next_block: "plan-approval",
    },
    {
      id: "plan-approval",
      label: "Plan approval",
      summary:
        "In interactive mode the plan is shown to the user, who approves it or asks for changes. Autonomous runs skip the gate. A mid-run replan also re-enters here.",
      next_block: "execute",
    },
    {
      id: "execute",
      label: "Execute plan steps",
      summary:
        "Run the approved units one at a time, recording one evidence entry per unit. The loop repeats until no unit remains.",
      outcome: "{{progress_execution_outcome}}",
      next_block: "verify",
    },
    {
      id: "verify",
      label: "Final review",
      summary:
        "An independent reviewer checks the actual result against the task contract. Confirmed defects are fixed and the review runs again.",
      outcome: "{{progress_review_outcome}}",
      next_block: "deliver",
    },
    {
      id: "deliver",
      label: "Present the result",
      summary:
        "Report the result truthfully. Interactive runs wait for the user to accept or request rework; autonomous runs present and end.",
      outcome: "{{progress_result_outcome}}",
    },
  ],
  nodeCount: 23,
};

export const SDF_WORKFLOW: AnnotatedWorkflow = {
  slug: "software-development-flow",
  title: "Software Development Flow",
  goal: "Deliver one complete repository change with its tests, permanent documentation, review, and truthful local closure.",
  version: "15.6.0",
  blocks: [
    {
      id: "intake",
      label: "Intake",
      summary:
        "Capture the task, its authority, and the project context; materialize the development standards; confirm requirements with the user when the run is interactive.",
      outcome: "{{progress_intake_outcome}}",
      next_block: "health",
    },
    {
      id: "health",
      label: "Project health",
      summary:
        "Run the smallest baseline checks that establish the repository's starting state, so later failures can be attributed to this change rather than inherited.",
      next_block: "plan",
    },
    {
      id: "plan",
      label: "Plan and plan review",
      summary:
        "Write the outcome-oriented unit plan and have it independently reviewed. Blocking findings send it back for repair; a plan-level defect returns to replanning.",
      outcome: "{{progress_plan_outcome}}",
      next_block: "plan-approval",
    },
    {
      id: "plan-approval",
      label: "Plan approval and activation",
      summary:
        "Interactive runs show the plan to the user and wait; a rejection produces a revised plan that goes back through review. Autonomous runs activate the reviewed plan directly.",
      next_block: "implement",
    },
    {
      id: "implement",
      label: "Implement a unit",
      summary:
        "Prepare the current unit against the repository as it stands, implement it, and write its truthful account. Repairs from later gates re-enter here.",
      outcome: "{{progress_implementation_outcome}}",
      next_block: "unit-validation",
    },
    {
      id: "unit-validation",
      label: "Unit validation gates",
      summary:
        "Deterministic checks, test adequacy, architecture review, and runtime validation, each with its own bounded repair loop. Any repair that reaches product behavior invalidates the evidence after it and returns to implementation.",
      outcome: "{{progress_tests_outcome}}",
      next_block: "broad-validation",
    },
    {
      id: "broad-validation",
      label: "Broad validation and documentation",
      summary:
        "Expensive suites, integration and packaging evidence, then permanent documentation updated from the actual diff once behavior has converged.",
      next_block: "completeness",
    },
    {
      id: "completeness",
      label: "Independent completeness review",
      summary:
        "A reviewer who did not write the unit judges it against its contract — code, tests, documentation, evidence. Gate-local corrections repair in place; product defects return to implementation.",
      outcome: "{{progress_review_outcome}}",
      next_block: "user-review",
    },
    {
      id: "user-review",
      label: "Unit review with the user",
      summary:
        "Interactive runs produce a step report and wait for the user's verdict on the unit. Feedback either repairs the unit or triggers a replan.",
      next_block: "checkpoint",
    },
    {
      id: "checkpoint",
      label: "Checkpoint and advance",
      summary:
        "Commit a local checkpoint when the run holds that authority, then move the plan cursor to the next unit or finish the plan.",
      outcome: "{{progress_checkpoint_outcome}}",
      next_block: "feature-validation",
    },
    {
      id: "feature-validation",
      label: "Feature-wide validation",
      summary:
        "Once every unit is closed, run the broad build, test, and packaging evidence the whole change requires.",
      next_block: "final-review",
    },
    {
      id: "final-review",
      label: "Final review and report",
      summary:
        "An independent semantic review of the complete diff against every requirement, a truthful final report, and — interactively — the user's acceptance of the feature.",
      next_block: "replan",
    },
    {
      id: "replan",
      label: "Replan",
      summary:
        "Entered when the plan no longer fits reality — from a teleport, from a review that found an upstream cause, or from closing the current unit early. A new complete plan revision is created and reviewed.",
      next_block: "finalize",
    },
    {
      id: "finalize",
      label: "Finalize",
      summary:
        "When the run holds commit authority, finalize the feature in version control with bounded retries; then notify completion.",
      outcome: "{{progress_finalize_outcome}}",
      next_block: "stopped",
    },
    {
      id: "stopped",
      label: "Stopped",
      summary:
        "The run ends without a delivered result, telling the user why. Reached only from an unresolved blocker or an unapproved closure.",
    },
  ],
  nodeCount: 130,
};
