/**
 * Workflow Mutation Service - Centralized workflow mutation with validation caching
 *
 * Issue #463: Performance optimization for workflow list
 *
 * This service is the SINGLE entry point for all workflow mutations:
 * - Create new workflows
 * - Update existing workflows
 * - Import workflows
 *
 * Key responsibility:
 * - Validate workflow graph before save using GraphValidator
 * - Cache validation result in database (isValid, validationErrors, validatedAt)
 * - Return validation result to caller for immediate feedback
 *
 * All validation errors are captured and stored, not thrown - allows saving
 * invalid workflows while tracking their status for the list endpoint.
 */

import type { WorkflowGraph } from "@mcp-moira/workflow-engine";
import { GraphValidator } from "@mcp-moira/workflow-engine";
import type {
  WorkflowRepository,
  ValidationCache,
} from "../database/repositories/workflow-repository.js";
import type { AuditRepository } from "../database/repositories/audit-repository.js";
import { createLogger, Component } from "../logging/logger.js";
import { AuditAction } from "../audit/actions.js";
import { getAuditSource } from "../logging/context.js";

/**
 * Options for saving a workflow via mutation service
 */
export interface MutationSaveOptions {
  /** Workflow graph to save */
  graph: WorkflowGraph;
  /** User ID performing the mutation */
  userId: string;
  /** Optional slug (auto-generated if not provided) */
  slug?: string;
  /** Visibility setting */
  visibility?: "public" | "private";
  /** Skip audit logging (for internal operations) */
  skipAudit?: boolean;
  /**
   * Admin bypass flag - allows updating workflow owned by another user
   * IMPORTANT: Caller MUST verify admin role before setting this flag
   */
  adminBypass?: boolean;
}

/**
 * Result of saving a workflow
 */
export interface MutationSaveResult {
  /** Workflow ID (UUID) */
  id: string;
  /** Workflow slug */
  slug: string;
  /** Validation result */
  validation: ValidationCache;
  /** Whether this was a new workflow (true) or update (false) */
  isNew: boolean;
}

/**
 * Result of migration batch
 */
export interface MigrationBatchResult {
  /** Number of workflows processed */
  processed: number;
  /** Number of valid workflows */
  valid: number;
  /** Number of invalid workflows */
  invalid: number;
  /** Whether there are more workflows to process */
  hasMore: boolean;
}

export class WorkflowMutationService {
  private logger = createLogger({ component: Component.Workflow });
  private validator: GraphValidator;
  private initialized = false;

  constructor(
    private workflowRepo: WorkflowRepository,
    private auditRepo: AuditRepository,
    validator?: GraphValidator,
  ) {
    // Allow injecting validator for testing
    this.validator = validator || new GraphValidator();
  }

  /**
   * Initialize service and run migration for unvalidated workflows
   * Call this once at application startup
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    this.logger.info("WorkflowMutationService initializing, running validation migration");

    // Migrate all unvalidated workflows
    let totalProcessed = 0;
    let totalValid = 0;
    let totalInvalid = 0;
    let hasMore = true;

    while (hasMore) {
      const result = await this.migrateUnvalidatedWorkflows(100);
      totalProcessed += result.processed;
      totalValid += result.valid;
      totalInvalid += result.invalid;
      hasMore = result.hasMore;
    }

    this.logger.info("Validation migration complete", {
      totalProcessed,
      totalValid,
      totalInvalid,
    });

    this.initialized = true;
  }

  /**
   * Save workflow with validation caching
   *
   * This is the primary mutation method. It:
   * 1. Validates the workflow graph
   * 2. Saves the workflow to database
   * 3. Caches validation result
   * 4. Returns combined result
   *
   * Validation errors do NOT prevent saving - invalid workflows are stored
   * with their validation status cached for the list endpoint.
   */
  async save(options: MutationSaveOptions): Promise<MutationSaveResult> {
    const { graph, userId, slug, visibility = "private", skipAudit, adminBypass } = options;

    // Check if this is an update (workflow exists)
    const ownership = await this.workflowRepo.getOwnership(graph.id);
    const isNew = !ownership.exists;

    // 1. Validate workflow graph
    // id is server-assigned (optional in the definition schema), so a graph
    // without id is valid here; the real id is generated by workflowRepo.save.
    const validationResult = await this.validator.validateWorkflow(graph);
    const isValid = validationResult.valid;
    const errors = validationResult.errors.map((e) => e.message);

    this.logger.debug("Workflow validated", {
      workflowId: graph.id,
      isValid,
      errorCount: errors.length,
    });

    // 2. Save workflow to database
    const saveResult = await this.workflowRepo.save({
      graph,
      userId,
      slug,
      visibility,
      adminBypass,
    });

    // 3. Cache validation result
    await this.workflowRepo.updateValidationCache(saveResult.id, isValid, errors);

    // 4. Audit log (unless skipped)
    if (!skipAudit) {
      const action = isNew ? AuditAction.WORKFLOW_CREATE : AuditAction.WORKFLOW_EDIT;
      await this.auditRepo.log({
        userId,
        action,
        resource: "workflow",
        resourceId: saveResult.id,
        source: getAuditSource(),
        metadata: JSON.stringify({
          name: graph.metadata.name,
          version: graph.metadata.version,
          slug: saveResult.slug,
          visibility,
          nodeCount: graph.nodes?.length || 0,
          isValid,
          validationErrorCount: errors.length,
        }),
      });
    }

    this.logger.info("Workflow saved with validation cache", {
      workflowId: saveResult.id,
      slug: saveResult.slug,
      isNew,
      isValid,
      validationErrorCount: errors.length,
    });

    return {
      id: saveResult.id,
      slug: saveResult.slug,
      validation: {
        status: isValid ? "valid" : "invalid",
        errors,
        validatedAt: Date.now(),
      },
      isNew,
    };
  }

  /**
   * Validate workflow graph without saving
   * Useful for preview/check operations
   */
  async validate(graph: WorkflowGraph): Promise<ValidationCache> {
    const validationResult = await this.validator.validateWorkflow(graph);
    const isValid = validationResult.valid;
    const errors = validationResult.errors.map((e) => e.message);

    return {
      status: isValid ? "valid" : "invalid",
      errors,
      validatedAt: Date.now(),
    };
  }

  /**
   * Migrate a batch of unvalidated workflows
   *
   * Processes workflows with isValid=null (unknown state) and caches their
   * validation status. Called during service initialization and can be
   * called manually for incremental migration.
   *
   * @param batchSize - Maximum number of workflows to process in this batch
   * @returns Migration result with counts and hasMore flag
   */
  async migrateUnvalidatedWorkflows(batchSize: number = 100): Promise<MigrationBatchResult> {
    const unvalidated = await this.workflowRepo.getUnvalidatedWorkflows(batchSize);

    if (unvalidated.length === 0) {
      return {
        processed: 0,
        valid: 0,
        invalid: 0,
        hasMore: false,
      };
    }

    let valid = 0;
    let invalid = 0;

    for (const { id, graph } of unvalidated) {
      try {
        const validationResult = await this.validator.validateWorkflow(graph);
        const isValid = validationResult.valid;
        const errors = validationResult.errors.map((e) => e.message);

        await this.workflowRepo.updateValidationCache(id, isValid, errors);

        if (isValid) {
          valid++;
        } else {
          invalid++;
        }
      } catch (error) {
        // If validation throws, mark as invalid with error message
        const errorMessage = error instanceof Error ? error.message : String(error);
        await this.workflowRepo.updateValidationCache(id, false, [
          `Validation failed: ${errorMessage}`,
        ]);
        invalid++;

        this.logger.warn("Workflow validation failed during migration", {
          workflowId: id,
          error: errorMessage,
        });
      }
    }

    this.logger.debug("Migration batch complete", {
      processed: unvalidated.length,
      valid,
      invalid,
    });

    // Check if there are more unvalidated workflows
    const remaining = await this.workflowRepo.getUnvalidatedWorkflows(1);

    return {
      processed: unvalidated.length,
      valid,
      invalid,
      hasMore: remaining.length > 0,
    };
  }

  /**
   * Re-validate a specific workflow and update cache
   * Useful when validation rules change
   */
  async revalidate(workflowId: string, userId: string): Promise<ValidationCache | null> {
    const graph = await this.workflowRepo.get(workflowId, userId);
    if (!graph) {
      return null;
    }

    const validationResult = await this.validator.validateWorkflow(graph);
    const isValid = validationResult.valid;
    const errors = validationResult.errors.map((e) => e.message);

    await this.workflowRepo.updateValidationCache(workflowId, isValid, errors);

    this.logger.info("Workflow revalidated", {
      workflowId,
      isValid,
      errorCount: errors.length,
    });

    return {
      status: isValid ? "valid" : "invalid",
      errors,
      validatedAt: Date.now(),
    };
  }
}
