/**
 * Checklist Flow Scenarios for software-development-flow
 *
 * Tests project checklist validation paths.
 */

import type { TestScenario } from "../../../helpers/scenario-runner.js";
import * as inputs from "./base-inputs.js";

export const checklistFlowScenarios: TestScenario[] = [
  // Scenario 1: Checklist validation passes
  {
    name: "Checklist validation passes",
    description: "All checklist items completed on first check",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      // Checklist passes
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 2: Checklist validation fails, fixed
  {
    name: "Checklist validation fails and fixed",
    description: "Some checklist items incomplete, fixed, then passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "create-iteration-workspace-checklist": {
        step_results_file: "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
      },
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      // Checklist fails first, then passes
      "check-project-checklist": [inputs.checklistFailed, inputs.checklistPassed],
      "fix-checklist-issues": inputs.checklistFixed,
      "document-checklist-fixes": inputs.checklistFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 3: No checklist (skipped)
  {
    name: "No project checklist",
    description: "Project has no checklist, validation skipped",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.artifactDiscoveryNoChecklist,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "ask-user-checklist": inputs.userDeclinesChecklist,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 4: Multiple checklist fix iterations
  {
    name: "Multiple checklist fix iterations",
    description: "Checklist requires multiple fix attempts",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
        },
      ],
      "create-iteration-workspace-checklist": [
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-4/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-5/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      // Checklist fails twice, then passes
      "check-project-checklist": [
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistPassed,
      ],
      "fix-checklist-issues": [inputs.checklistFixed, inputs.checklistFixed],
      "document-checklist-fixes": [
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
      ],
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 5: Checklist iteration limit reached - user aborts
  // Flow: checklist fails 3 times → iteration limit reached → user chooses abort → document abort state → end
  {
    name: "Checklist iteration limit - abort",
    description:
      "Checklist fix iteration limit reached, user aborts after 3 failed checklist fix attempts",
    expect: { status: "completed", maxSteps: 250 },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      // 1 initial iteration + 9 checklist fix iterations (10th hits escalation)
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "create-iteration-workspace-checklist": [
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-4/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-5/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-6/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-7/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-8/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-9/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-10/step-results.md",
        },
      ],
      // 10 iterations through startup (all succeed)
      "restart-and-rebuild": [
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
      ],
      "analyze-implementation-changes": [
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
      ],
      "analyze-code-changes": [
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
      ],
      "verify-functionality-manually": [
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
      ],
      "run-all-tests": [
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
        inputs.allTestsPass,
      ],
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "check-code-quality-and-architecture": [
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
      ],
      "check-browser-impact": [
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
      ],
      "assess-testing-needs": [
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
      ],
      "update-step-documentation": [
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
      ],
      // Agent validation passes each time before reaching checklist
      "agent-validate-step": [
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
        inputs.agentValidationPassed,
      ],
      // Checklist fails all 10 times
      "check-project-checklist": [
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
        inputs.checklistFailed,
      ],
      "fix-checklist-issues": [
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
        inputs.checklistFixed,
      ],
      "document-checklist-fixes": [
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
        inputs.checklistFixesDocumented,
      ],
      // After 10th checklist fix attempt, iteration limit reached → escalate → user aborts
      "escalate-iteration-limit": inputs.escalationAbort,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "document-abort-state": {},
    },
  },
];
