/**
 * Edge Case Scenarios for software-development-flow
 *
 * Tests edge cases: browser validation, new tests, multiple iterations, etc.
 */

import type { TestScenario } from "../../../helpers/scenario-runner.js";
import * as inputs from "./base-inputs.js";

export const edgeCaseScenarios: TestScenario[] = [
  // Scenario 1: Browser validation required and passes
  {
    name: "Browser testing required and passes",
    description: "UI changes require browser testing which passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      // Browser testing required
      "check-browser-impact": inputs.browserTestingRequired,
      "validate-browser-functionality": inputs.browserValidationPassed,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 2: Browser validation fails and fixed
  {
    name: "Browser testing fails and fixed",
    description: "Browser testing fails, issues fixed, then passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.browserTestingRequired,
      // Browser validation fails first, then passes
      "validate-browser-functionality": [
        inputs.browserValidationFailed,
        inputs.browserValidationPassed,
      ],
      "fix-broken-functionality-action": inputs.functionalityFixed,
      "document-functionality-fixes": inputs.functionalityFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 3: New tests required
  // Flow: assess-testing-needs (need tests) → write → document → assess-testing-needs (all covered) → continue
  {
    name: "New tests required",
    description: "New functionality requires new tests to be written",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      // Need to run tests after writing new ones too
      "run-all-tests": [inputs.allTestsPass, inputs.allTestsPass],
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      // First: needs tests, Second (after write): all covered
      "assess-testing-needs": [inputs.newTestsRequired, inputs.noNewTestsRequired],
      "write-new-tests-action": inputs.newTestsWritten,
      "document-new-tests": inputs.newTestsDocumented,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 4: No browser UI in project
  {
    name: "No browser UI in project",
    description: "Project has no browser UI, skip browser checks entirely",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.artifactDiscoveryNoBrowser,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "ask-user-browser-ui": inputs.userDeclinesBrowserUI,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      // Skip browser checks (route-has-browser-ui: false)
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 5: Browser impact check - no testing needed
  {
    name: "Browser impact - no testing needed",
    description: "Changes don't impact browser, skip browser testing",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      // Browser impact check - no testing needed
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 6: Skip initial tests
  {
    name: "Skip initial tests",
    description: "No test info, skip initial test run",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.artifactDiscoveryNoTests,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "ask-user-test-info": inputs.userDeclinesTests,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      // Skip initial-run-tests (route-skip-initial-tests: true)
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      // Skip run-all-tests (route-skip-run-tests: true)
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 7: No documentation standards
  {
    name: "No documentation standards",
    description: "Project has no doc standards, skip documentation validation",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.artifactDiscoveryNoDocs,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "ask-user-docs-standards": inputs.userDeclinesDocsStandards,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 8: Incomplete implementation needs fixing
  // Flow: check-implementation-completeness:false → fix-incomplete-implementation-action → document → iteration loop
  {
    name: "Incomplete implementation fixed",
    description: "Not all tasks completed, fixed in next iteration",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      // First: incomplete, Second: complete
      "check-implementation-completeness": [
        inputs.implementationIncomplete,
        inputs.implementationComplete,
      ],
      "fix-incomplete-implementation-action": inputs.incompleteFixed,
      "document-completion-fixes": inputs.completionFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 9: User aborts after iteration limit (3 failed fix attempts)
  {
    name: "User aborts after iteration limit",
    description: "After 3 fix attempts (max_fix_iterations=3), user decides to abort",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      // 4 iterations (initial + 3 fix attempts)
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-4/step-results.md",
        },
      ],
      // Need analyze-implementation-changes for each iteration
      "analyze-implementation-changes": [
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
      ],
      // Startup keeps failing 4 times (initial + 3 fix attempts, but escalation on 3rd fix)
      "restart-and-rebuild": [
        inputs.startupFailed,
        inputs.startupFailed,
        inputs.startupFailed,
        inputs.startupFailed,
      ],
      "fix-startup-issues-action": [inputs.startupFixed, inputs.startupFixed, inputs.startupFixed],
      "document-startup-fixes": [
        inputs.startupFixDocumented,
        inputs.startupFixDocumented,
        inputs.startupFixDocumented,
      ],
      // After 3rd fix attempt, escalation triggered (fix_iteration_count=3 >= max_fix_iterations=3)
      "escalate-iteration-limit": inputs.escalationAbort,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // document-abort-state has no inputSchema, expects empty input
      "document-abort-state": {},
    },
  },

  // Scenario 10: Complex multi-issue fix cycle
  {
    name: "Complex multi-issue fix cycle",
    description: "Multiple issues discovered during validation, all fixed",
    expect: { status: "completed", maxSteps: 200 },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
        },
      ],
      // Startup fails first
      "restart-and-rebuild": [inputs.startupFailed, inputs.startupSuccess],
      "fix-startup-issues-action": inputs.startupFixed,
      "document-startup-fixes": inputs.startupFixDocumented,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      // Functionality fails first
      "verify-functionality-manually": [inputs.someFunctionsBroken, inputs.allFunctionsWorking],
      "fix-broken-functionality-action": inputs.functionalityFixed,
      "document-functionality-fixes": inputs.functionalityFixesDocumented,
      // Tests fail first
      "run-all-tests": [inputs.someTestsFail, inputs.allTestsPass],
      "analyze-test-failures": inputs.testFailureFixCode,
      "fix-implementation-for-tests-action": inputs.testsFixedByCode,
      "document-test-fixes": inputs.testFixesDocumented,
      // Escalation may trigger after multiple fix cycles
      "escalate-iteration-limit": inputs.escalationContinue,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },
  // === BOUNDED LOOP ESCAPE SCENARIOS ===
  // These cover the false branch of review-fix-limit conditions (counter >= max)

  // Plan review fix limit escape
  {
    name: "Plan review fix limit escape",
    description: "Agent review finds issues 3 times, escapes to notify-plan-ready",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      // 3 reviews with issues → counter reaches 3 → escape
      "agent-review-plan": [
        inputs.planReviewWithIssues,
        inputs.planReviewWithIssues,
        inputs.planReviewWithIssues,
      ],
      "fix-plan-issues": [{}, {}],
      // Limit reached → user continues → escaped to notify-plan-ready
      "ask-user-plan-review-limit-reached": { plan_review_limit_decision: "continue" },
      // → present-plan-to-user
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Refinement review fix limit escape
  {
    name: "Refinement review fix limit escape",
    description: "Refinement review finds issues 3 times, escapes to notify-plan-refined",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planRejected,
      "create-plan-change-reasons": inputs.planChangeReasonsDocumented,
      "refine-development-plan": inputs.planRefinement,
      // 3 refinement reviews with issues → escape
      "review-refined-plan": [
        inputs.refinementReviewFailed,
        inputs.refinementReviewFailed,
        inputs.refinementReviewFailed,
      ],
      "fix-refined-plan-issues": [{}, {}],
      // Limit reached → user continues → escaped to notify-plan-refined
      "ask-user-refine-review-limit-reached": { refine_review_limit_decision: "continue" },
      // → confirm-plan-refinement
      "confirm-plan-refinement": inputs.refinementApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Extension review fix limit escape
  {
    name: "Extension review fix limit escape",
    description: "Extension review finds issues 3 times, escapes to notify-plan-extended",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      // Step 1 + Step 2
      "create-initial-iteration-workspace": [
        inputs.standardInitialIterationWorkspace,
        inputs.standardInitialIterationWorkspace,
      ],
      "implement-step": [
        inputs.standardImplementation,
        { implemented_functionality: "Added extension step implementation" },
      ],
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-2/iteration-1/step-results.md",
        },
      ],
      "restart-and-rebuild": [inputs.startupSuccess, inputs.startupSuccess],
      "analyze-implementation-changes": [inputs.codeChanges, inputs.codeChanges],
      "analyze-code-changes": [inputs.codeAnalysisWithFunctions, inputs.codeAnalysisWithFunctions],
      "verify-functionality-manually": [inputs.allFunctionsWorking, inputs.allFunctionsWorking],
      "run-all-tests": [inputs.allTestsPass, inputs.allTestsPass],
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "check-code-quality-and-architecture": [inputs.qualityCheckPassed, inputs.qualityCheckPassed],
      "check-browser-impact": [inputs.noBrowserTesting, inputs.noBrowserTesting],
      "assess-testing-needs": [inputs.noNewTestsRequired, inputs.noNewTestsRequired],
      "update-step-documentation": [
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
      ],
      "check-project-checklist": [inputs.checklistPassed, inputs.checklistPassed],
      "agent-validate-step": [inputs.agentValidationPassed, inputs.agentValidationPassed],
      "commit-step": [inputs.commitStep, inputs.commitStep],
      "check-user-approval-needed": [inputs.userApprovalNotNeeded, inputs.userApprovalNotNeeded],
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": [inputs.finalReportGenerated, inputs.finalReportGeneratedV2],
      "read-prior-report": inputs.priorReportRead,
      "present-results": [inputs.userPermissionGranted, inputs.userPermissionGranted],
      // Step 1 → not satisfied → extension, Step 2 → satisfied
      "collect-user-feedback": [inputs.userNotSatisfied, inputs.userSatisfied],
      "record-user-feedback-to-requirements": inputs.userFeedbackRecorded,
      "create-plan-change-reasons": inputs.planChangeReasonsDocumented,
      "create-additional-steps": inputs.additionalStepsCreated,
      // 3 extension reviews fail → escape
      "review-extended-plan": [
        inputs.extensionReviewFailed,
        inputs.extensionReviewFailed,
        inputs.extensionReviewFailed,
      ],
      "fix-extension-plan-issues": [{}, {}],
      // Limit reached → user continues → escaped to notify-plan-extended
      "ask-user-extend-review-limit-reached": { extend_review_limit_decision: "continue" },
      // → confirm-plan-extension
      "confirm-plan-extension": inputs.extensionApproved,
      "set-extension-total-steps": { total_steps: 2 },
      "get-next-step-name": { current_step_name: "Extension step" },
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Update review fix limit escape
  {
    name: "Update review fix limit escape",
    description: "Update review finds issues 3 times, escapes to confirm-plan-update",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      // Iteration 1 (fails with plan update) + Iteration 2 (after reinitialize, passes)
      "create-initial-iteration-workspace": [
        inputs.standardInitialIterationWorkspace,
        inputs.standardInitialIterationWorkspace,
      ],
      "implement-step": [
        inputs.standardImplementation,
        { implemented_functionality: "Updated implementation after plan change" },
      ],
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": [inputs.startupSuccess, inputs.startupSuccess],
      "analyze-implementation-changes": [inputs.codeChanges, inputs.codeChanges],
      "analyze-code-changes": [inputs.codeAnalysisWithFunctions, inputs.codeAnalysisWithFunctions],
      "verify-functionality-manually": [inputs.allFunctionsWorking, inputs.allFunctionsWorking],
      "run-all-tests": [inputs.allTestsPass, inputs.allTestsPass],
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "check-code-quality-and-architecture": [inputs.qualityCheckPassed, inputs.qualityCheckPassed],
      "check-browser-impact": [inputs.noBrowserTesting, inputs.noBrowserTesting],
      "assess-testing-needs": [inputs.noNewTestsRequired, inputs.noNewTestsRequired],
      "update-step-documentation": [
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
      ],
      "check-project-checklist": [inputs.checklistPassed, inputs.checklistPassed],
      // Iter 1: fails with plan update, Iter 2: passes
      "agent-validate-step": [
        inputs.agentValidationFailedWithPlanUpdate,
        inputs.agentValidationPassed,
      ],
      "fix-agent-feedback-issues-action": inputs.fixAgentFeedbackWithPlanUpdate,
      "approve-current-step-before-replan": inputs.approveCurrentStepBeforeReplan,
      "create-plan-change-reasons": inputs.planChangeReasonsDocumented,
      "update-plan-during-execution": inputs.planUpdateDuringExecution,
      "review-updated-plan": [
        inputs.planUpdateReviewFailed,
        inputs.planUpdateReviewFailed,
        inputs.planUpdateReviewFailed,
      ],
      "fix-updated-plan-issues": [{}, {}],
      // Limit reached → user continues → escaped to confirm-plan-update
      "ask-user-update-review-limit-reached": { update_review_limit_decision: "continue" },
      // → confirm-plan-update
      "confirm-plan-update": inputs.planUpdateApproved,
      "set-update-total-steps": { total_steps: 2 },
      "reinitialize-plan-tracking": {
        tracking_reinitialized: "yes",
      },
      // After iter 2 passes (singular — only one more pass after reinitialize)
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "get-next-step-name": inputs.nextStepName,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Teleport: Agent teleports from implementation to plan rewriting
  {
    name: "Teleport from implementation to replan",
    description:
      "Agent realizes during implementation that plan needs restructuring, teleports to replan branch",
    expect: {
      status: "completed",
      reaches: ["teleport-replan", "expr-reset-for-replan", "update-plan-during-execution"],
    },
    teleportAfter: {
      afterNode: "implement-step",
      visitNumber: 1,
      teleportTo: "teleport-replan",
    },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      // First visit to implement-step → teleport fires after this
      "implement-step": [inputs.standardImplementation, inputs.standardImplementation],
      // Teleport replan
      "teleport-replan": inputs.teleportReplanAssessment,
      // After reset → save-rework-context → create-plan-change-reasons → update-plan-during-execution
      "save-rework-context": inputs.reworkContextSaved,
      "create-plan-change-reasons": inputs.planChangeReasonsDocumented,
      "update-plan-during-execution": inputs.planUpdateDuringExecution,
      "review-updated-plan": inputs.planUpdateReviewPassed,
      "confirm-plan-update": inputs.planUpdateApproved,
      "set-update-total-steps": { total_steps: 2 },
      "reinitialize-plan-tracking": {
        tracking_reinitialized: "yes",
      },
      // After plan update, continues from create-initial-iteration-workspace (2nd step impl)
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "get-next-step-name": inputs.nextStepName,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Requirements confirmation rejection loop
  {
    name: "Requirements rejected then confirmed",
    description: "User rejects requirements, provides corrections, then confirms",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      // First visit: rejected, second visit: confirmed
      "present-requirements-confirmation": [
        inputs.requirementsRejected,
        inputs.requirementsConfirmed,
      ],
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "clarify-requirements": inputs.requirementsClarified,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },
  // === Requirements validation gap scenario ===
  {
    name: "Requirements gaps found triggers rework",
    description:
      "Requirements coverage validation finds gaps, routes to create-additional-steps for rework",
    expect: {
      status: "completed",
      reaches: [
        "validate-requirements-coverage",
        "check-requirements-gaps",
        "create-additional-steps",
      ],
    },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      // Step 1: standard pass
      "implement-step": [inputs.standardImplementation, inputs.standardImplementation],
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        inputs.standardIterationWorkspace,
      ],
      "restart-and-rebuild": [inputs.startupSuccess, inputs.startupSuccess],
      "analyze-implementation-changes": [inputs.codeChanges, inputs.codeChanges],
      "analyze-code-changes": [inputs.codeAnalysisWithFunctions, inputs.codeAnalysisWithFunctions],
      "verify-functionality-manually": [inputs.allFunctionsWorking, inputs.allFunctionsWorking],
      "run-all-tests": [inputs.allTestsPass, inputs.allTestsPass],
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "check-code-quality-and-architecture": [inputs.qualityCheckPassed, inputs.qualityCheckPassed],
      "check-browser-impact": [inputs.noBrowserTesting, inputs.noBrowserTesting],
      "assess-testing-needs": [inputs.noNewTestsRequired, inputs.noNewTestsRequired],
      "update-step-documentation": [
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
      ],
      "check-project-checklist": [inputs.checklistPassed, inputs.checklistPassed],
      "agent-validate-step": [inputs.agentValidationPassed, inputs.agentValidationPassed],
      "commit-step": [inputs.commitStep, inputs.commitStep],
      "check-user-approval-needed": [inputs.userApprovalNotNeeded, inputs.userApprovalNotNeeded],
      // First pass: gaps found → rework
      "validate-requirements-coverage": [
        inputs.requirementsCoverageWithGaps,
        inputs.requirementsCoverageValid,
      ],
      // Rework: create additional steps to fix gaps
      "create-plan-change-reasons": inputs.planChangeReasonsDocumented,
      "create-additional-steps": {
        additional_steps_created: [
          "Step 2: Implement missing authentication endpoints and session handling with tests",
        ],
        plan_changes_summary: "Added step 2 to cover requirements gaps",
      },
      "review-extended-plan": inputs.extensionReviewPassed,
      "confirm-plan-extension": inputs.extensionApproved,
      "set-extension-total-steps": { total_steps: 2 },
      "get-next-step-name": { current_step_name: "Cover requirements gaps" },
      "reinitialize-plan-tracking": {
        tracking_reinitialized: "yes",
      },
      // Second pass after gap fix
      "read-prior-report": inputs.priorReportRead,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // === Screenshot Validation Scenarios ===

  // Screenshot validation opt-in with passing validation
  {
    name: "Screenshot validation enabled and passes",
    description: "Screenshots enabled, infrastructure setup, validation passes, report generated",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      // Screenshots enabled
      "ask-screenshot-validation": inputs.screenshotValidationEnabled,
      // check-screenshot-validation[true] → setup-screenshot-infrastructure
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChangesWithUI,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      // route-screenshot-validation-enabled[true] → run-screenshot-validation
      "run-screenshot-validation": inputs.screenshotValidationPassed,
      // check-screenshot-results[true] → generate-screenshot-report
      "generate-screenshot-report": inputs.screenshotReportGenerated,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "user-review-step-with-screenshots": inputs.userReviewWithScreenshotsApproved,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Screenshot validation fix loop
  {
    name: "Screenshot validation fix loop",
    description: "Screenshots enabled, validation fails first, issues fixed, then passes on retry",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      // Screenshots enabled
      "ask-screenshot-validation": inputs.screenshotValidationEnabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChangesWithUI,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      // First run: fails (3 issues), second run: passes (0 issues)
      "run-screenshot-validation": [
        inputs.screenshotValidationFailed,
        inputs.screenshotValidationPassed,
      ],
      // check-screenshot-results[false] → fix-screenshot-issues
      "fix-screenshot-issues": inputs.screenshotIssuesFixed,
      "document-screenshot-fixes": inputs.screenshotFixesDocumented,
      // After screenshot fix, goes through expr-increment-iteration → iteration loop
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // check-screenshot-results[true] → generate-screenshot-report
      "generate-screenshot-report": inputs.screenshotReportGenerated,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "user-review-step-with-screenshots": inputs.userReviewWithScreenshotsApproved,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // UI changes without screenshot validation
  {
    name: "UI changes without screenshot validation",
    description:
      "Code has UI changes but screenshot validation is disabled, skips screenshot pipeline",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // UI changes but screenshots disabled → check-screenshot-change-type(true) → route-screenshot-validation-enabled(false) → skip
      "analyze-implementation-changes": inputs.codeChangesWithUI,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 20: Results rejection — user says no, then accepts after fix cycle
  {
    name: "Results rejection and fix",
    description: "User rejects results, fix cycle runs, then user accepts",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        inputs.standardIterationWorkspace,
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": [inputs.codeChanges, inputs.codeChanges],
      "analyze-code-changes": [inputs.codeAnalysisWithFunctions, inputs.codeAnalysisWithFunctions],
      "verify-functionality-manually": [inputs.allFunctionsWorking, inputs.allFunctionsWorking],
      "run-all-tests": [inputs.allTestsPass, inputs.allTestsPass],
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "check-code-quality-and-architecture": [inputs.qualityCheckPassed, inputs.qualityCheckPassed],
      "check-browser-impact": [inputs.noBrowserTesting, inputs.noBrowserTesting],
      "assess-testing-needs": [inputs.noNewTestsRequired, inputs.noNewTestsRequired],
      "update-step-documentation": [
        inputs.stepDocumentationUpdated,
        inputs.stepDocumentationUpdated,
      ],
      "check-project-checklist": [inputs.checklistPassed, inputs.checklistPassed],
      "agent-validate-step": [inputs.agentValidationPassed, inputs.agentValidationPassed],
      "commit-step": [inputs.commitStep, inputs.commitStep],
      "check-user-approval-needed": [inputs.userApprovalNotNeeded, inputs.userApprovalNotNeeded],
      "validate-requirements-coverage": [
        inputs.requirementsCoverageValid,
        inputs.requirementsCoverageValid,
      ],
      "generate-final-report": [inputs.finalReportGenerated, inputs.finalReportGenerated],
      "read-prior-report": inputs.priorReportRead,
      // First: user not satisfied → rejection flow → extend plan → re-implement
      "present-results": [inputs.userPermissionGranted, inputs.userPermissionGranted],
      "collect-user-feedback": [inputs.userNotSatisfied, inputs.userSatisfied],
      "record-user-feedback-to-requirements": inputs.userFeedbackRecorded,
      // Rejection flow: extend plan path
      "create-plan-change-reasons": inputs.planChangeReasonsDocumented,
      "create-additional-steps": inputs.additionalStepsCreated,
      "review-extended-plan": inputs.extensionReviewPassed,
      "confirm-plan-extension": inputs.extensionApproved,
      "set-extension-total-steps": { total_steps: 2 },
      "get-next-step-name": { current_step_name: "Fix user concerns" },
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // === Screenshot Guide Not Found Scenarios ===

  // Screenshot guide not found - user creates it
  {
    name: "Screenshot guide not found - user creates guide",
    description: "Screenshots enabled, guide not found, user opts to create guide infrastructure",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      // Override screenshot guide to not found
      "search-screenshot-guide": inputs.searchScreenshotGuideNotFound,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationEnabled,
      // route-screenshot-guide-found[false] → ask-user-screenshot-guide
      "ask-user-screenshot-guide": inputs.userWantsScreenshotGuide,
      // check-screenshot-guide-decision[true] → create-screenshot-guide
      "create-screenshot-guide": inputs.screenshotInfrastructureCreated,
      "present-screenshot-guide": inputs.approveArtifact,
      "collect-screenshot-guide-path": inputs.collectScreenshotGuidePath,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChangesWithUI,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "run-screenshot-validation": inputs.screenshotValidationPassed,
      "generate-screenshot-report": inputs.screenshotReportGenerated,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "user-review-step-with-screenshots": inputs.userReviewWithScreenshotsApproved,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Screenshot guide not found - user declines
  {
    name: "Screenshot guide not found - user declines guide",
    description:
      "Screenshots enabled, guide not found, user declines creating guide, continues without",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      // Override: screenshot guide not found in this scenario
      "search-screenshot-guide": inputs.searchScreenshotGuideNotFound,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationEnabled,
      // guide not found → ask user → declines
      "ask-user-screenshot-guide": inputs.userDeclinesScreenshotGuide,
      // check-screenshot-guide-decision[false] → expr-set-screenshot-guide-skip
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChangesWithUI,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      // route-has-screenshot-guide:false → run-screenshot-validation (guide was skipped)
      "run-screenshot-validation": inputs.screenshotValidationPassed,
      "generate-screenshot-report": inputs.screenshotReportGenerated,
      "commit-step": inputs.commitStep,
      // route-screenshot-approval-shortcut:true → forced user review with screenshots
      "user-review-step-with-screenshots": inputs.userReviewWithScreenshotsApproved,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // === Missing Info Scenarios (checklist/startup/onboarding not_found) ===

  // All info not found - user creates each
  {
    name: "All project info missing - user creates all",
    description: "All 7 artifact types not found, user creates each one",
    expect: { status: "completed" },
    mockInputs: {
      // All 7 search nodes return not_found
      "search-test-info": {
        test_info_path: "not_found",
        search_strategies_used:
          "1. grep -ri test README.md. 2. find . -name TESTING*. 3. ls tests/",
      },
      "ask-user-test-info": inputs.userRequestsTests,
      "create-test-info": inputs.createTestInfo,
      "present-test-info": inputs.approveArtifact,
      "collect-test-info-path": inputs.collectTestInfoPath,
      "search-docs-standards": {
        documentation_standards_path: "not_found",
        search_strategies_used:
          "1. find . -name *STYLE*. 2. grep -ri documentation-standard. 3. ls docs/",
      },
      "ask-user-docs-standards": inputs.userCreatesDocsStandards,
      "create-docs-standards": inputs.createDocsStandards,
      "present-docs-standards": inputs.approveArtifact,
      "collect-docs-standards-path": inputs.collectDocsStandardsPath,
      "search-browser-ui": {
        browser_ui_info_path: "not_found",
        search_strategies_used:
          "1. find . -name package.json -path */web*. 2. ls packages/. 3. grep -ri browser-ui",
      },
      "ask-user-browser-ui": inputs.userRequestsBrowserUI,
      "create-browser-ui": inputs.createBrowserUI,
      "present-browser-ui": inputs.approveArtifact,
      "collect-browser-ui-path": inputs.collectBrowserUIPath,
      "search-checklist": {
        project_checklist_path: "not_found",
        search_strategies_used: "1. find . -name *CHECKLIST*. 2. grep -ri checklist. 3. ls docs/",
      },
      "ask-user-checklist": inputs.userCreatesChecklist,
      "create-checklist": inputs.createChecklist,
      "present-checklist": inputs.approveArtifact,
      "collect-checklist-path": inputs.collectChecklistPath,
      "search-startup-info": {
        startup_info_path: "not_found",
        search_strategies_used:
          "1. grep -ri startup docs/. 2. find . -name DEVELOPMENT*. 3. ls docs/",
      },
      "ask-user-startup-info": inputs.userCreatesStartupInfo,
      "create-startup-info": inputs.createStartupInfo,
      "present-startup-info": inputs.approveArtifact,
      "collect-startup-info-path": inputs.collectStartupInfoPath,
      "search-onboarding-info": {
        agent_onboarding_file_path: "not_found",
        search_strategies_used: "1. ls . 2. grep -ri onboarding. 3. find . -name *onboard*",
      },
      "ask-user-onboarding-info": inputs.userCreatesOnboardingInfo,
      "create-onboarding-info": inputs.createOnboardingInfo,
      "present-onboarding-info": inputs.approveArtifact,
      "collect-onboarding-info-path": inputs.collectOnboardingInfoPath,
      "search-screenshot-guide": {
        screenshot_guide_path: "not_found",
        search_strategies_used:
          "1. find . -name *screenshot*. 2. grep -ri screenshot docs/. 3. ls docs/",
      },
      "ask-user-screenshot-guide": inputs.userWantsScreenshotGuide,
      "create-screenshot-guide": inputs.createScreenshotGuide,
      "present-screenshot-guide": inputs.approveArtifact,
      "collect-screenshot-guide-path": inputs.collectScreenshotGuidePath,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Artifact rejection loop — user rejects first version, approves second for ALL 7 artifacts
  {
    name: "All artifacts rejected then approved on retry",
    description:
      "All 7 artifacts rejected once, re-created, then approved — covers all check-*-approval false branches",
    expect: { status: "completed" },
    mockInputs: {
      // All 7 search nodes return not_found
      "search-test-info": {
        test_info_path: "not_found",
        search_strategies_used:
          "1. grep -ri test README.md. 2. find . -name TESTING*. 3. ls tests/",
      },
      "ask-user-test-info": inputs.userRequestsTests,
      "create-test-info": inputs.createTestInfo,
      "present-test-info": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-test-info-path": inputs.collectTestInfoPath,
      "search-docs-standards": {
        documentation_standards_path: "not_found",
        search_strategies_used:
          "1. find . -name *STYLE*. 2. grep -ri documentation-standard. 3. ls docs/",
      },
      "ask-user-docs-standards": inputs.userCreatesDocsStandards,
      "create-docs-standards": inputs.createDocsStandards,
      "present-docs-standards": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-docs-standards-path": inputs.collectDocsStandardsPath,
      "search-browser-ui": {
        browser_ui_info_path: "not_found",
        search_strategies_used:
          "1. find . -name package.json -path */web*. 2. ls packages/. 3. grep -ri browser-ui",
      },
      "ask-user-browser-ui": inputs.userRequestsBrowserUI,
      "create-browser-ui": inputs.createBrowserUI,
      "present-browser-ui": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-browser-ui-path": inputs.collectBrowserUIPath,
      "search-checklist": {
        project_checklist_path: "not_found",
        search_strategies_used: "1. find . -name *CHECKLIST*. 2. grep -ri checklist. 3. ls docs/",
      },
      "ask-user-checklist": inputs.userCreatesChecklist,
      "create-checklist": inputs.createChecklist,
      "present-checklist": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-checklist-path": inputs.collectChecklistPath,
      "search-startup-info": {
        startup_info_path: "not_found",
        search_strategies_used:
          "1. grep -ri startup docs/. 2. find . -name DEVELOPMENT*. 3. ls docs/",
      },
      "ask-user-startup-info": inputs.userCreatesStartupInfo,
      "create-startup-info": inputs.createStartupInfo,
      "present-startup-info": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-startup-info-path": inputs.collectStartupInfoPath,
      "search-onboarding-info": {
        agent_onboarding_file_path: "not_found",
        search_strategies_used: "1. ls . 2. grep -ri onboarding. 3. find . -name *onboard*",
      },
      "ask-user-onboarding-info": inputs.userCreatesOnboardingInfo,
      "create-onboarding-info": inputs.createOnboardingInfo,
      "present-onboarding-info": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-onboarding-info-path": inputs.collectOnboardingInfoPath,
      "search-screenshot-guide": {
        screenshot_guide_path: "not_found",
        search_strategies_used:
          "1. find . -name *screenshot*. 2. grep -ri screenshot docs/. 3. ls docs/",
      },
      "ask-user-screenshot-guide": inputs.userWantsScreenshotGuide,
      "create-screenshot-guide": inputs.createScreenshotGuide,
      "present-screenshot-guide": [inputs.rejectArtifact, inputs.approveArtifact],
      "collect-screenshot-guide-path": inputs.collectScreenshotGuidePath,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // === Skip Routes (false branches) ===

  // Skip foundation + skip startup + skip restart
  {
    name: "All skip routes take false branch",
    description:
      "agent_onboarding_info=skip skips foundation study, startup_info=skip skips startup and restart",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.artifactDiscoveryAllFound,
      // Override startup and onboarding as not found
      "search-startup-info": {
        startup_info_path: "not_found",
        search_strategies_used:
          "1. grep -ri startup docs/. 2. find . -name DEVELOPMENT*. 3. ls docs/",
      },
      "search-onboarding-info": {
        agent_onboarding_file_path: "not_found",
        search_strategies_used: "1. ls . 2. grep -ri onboarding. 3. find . -name *onboard*",
      },
      // route-startup-info-found[false] → ask-user-startup-info (user declines → skip → route-skip-startup[false])
      "ask-user-startup-info": inputs.userDeclinesStartupInfo,
      // route-onboarding-info-found[false] → ask-user-onboarding-info (user declines → skip → route-skip-foundation[false])
      "ask-user-onboarding-info": inputs.userDeclinesOnboarding,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      // route-skip-foundation[false] → study-implementation-details (skips study-project-foundation)
      // route-skip-startup[false] → notify-step-start (skips initial-system-startup)
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      // initial-system-startup SKIPPED by route-skip-startup[false]
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      // restart-and-rebuild SKIPPED by route-skip-restart[false]
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // No checklist - route-has-checklist[false] → check-screenshot-change-type
  {
    name: "No checklist skips to screenshot change type check",
    description: "project_checklist=skip triggers route-has-checklist false branch",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.artifactDiscoveryNoChecklist,
      ...inputs.gitOpsCleanRepo,
      ...inputs.workspaceSetup,
      // route-checklist-info-found[false] → ask-user-create-checklist (project_checklist="skip")
      "ask-user-checklist": inputs.userDeclinesChecklist,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },
];
