/**
 * Fix Cycle Scenarios for software-development-flow
 *
 * Tests paths where issues are found and need to be fixed in iteration loops.
 */

import type { TestScenario } from "../../../helpers/scenario-runner.js";
import * as inputs from "./base-inputs.js";

export const fixCycleScenarios: TestScenario[] = [
  // Scenario 1: Fix startup issues
  {
    name: "Fix startup issues",
    description: "Startup fails, gets fixed, then succeeds",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      // First attempt: startup fails
      "restart-and-rebuild": [inputs.startupFailed, inputs.startupSuccess],
      // Fix startup issues
      "fix-startup-issues-action": inputs.startupFixed,
      "document-startup-fixes": inputs.startupFixDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 2: Fix test failures (fix code strategy)
  {
    name: "Fix test failures - fix code",
    description: "Tests fail, code is fixed, tests pass",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      // First attempt: tests fail
      "run-all-tests": [inputs.someTestsFail, inputs.allTestsPass],
      "analyze-test-failures": inputs.testFailureFixCode,
      "fix-implementation-for-tests-action": inputs.testsFixedByCode,
      "document-test-fixes": inputs.testFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 3: Fix test failures (update tests strategy)
  {
    name: "Fix test failures - update tests",
    description: "Tests fail, tests are updated, tests pass",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      // First attempt: tests fail
      "run-all-tests": [inputs.someTestsFail, inputs.allTestsPass],
      "analyze-test-failures": inputs.testFailureUpdateTests,
      "update-tests-for-changes": inputs.testsUpdated,
      // After fix: continue
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 4: Fix code quality issues
  {
    name: "Fix code quality issues",
    description: "Quality check fails, issues fixed, check passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      // First attempt: quality check fails
      "check-code-quality-and-architecture": [inputs.qualityCheckFailed, inputs.qualityCheckPassed],
      "fix-code-quality-and-architecture-action": inputs.qualityFixed,
      "document-quality-architecture-fixes": inputs.qualityFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 5: Fix functionality issues
  {
    name: "Fix functionality issues",
    description: "Some functions broken, fixed, all work",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      // First attempt: some functions broken
      "verify-functionality-manually": [inputs.someFunctionsBroken, inputs.allFunctionsWorking],
      "fix-broken-functionality-action": inputs.functionalityFixed,
      "document-functionality-fixes": inputs.functionalityFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 6: Fix incomplete implementation
  {
    name: "Fix incomplete implementation",
    description: "Implementation incomplete, completed, check passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      // First attempt: incomplete
      "check-implementation-completeness": [
        inputs.implementationIncomplete,
        inputs.implementationComplete,
      ],
      "fix-incomplete-implementation-action": inputs.incompleteFixed,
      "document-completion-fixes": inputs.completionFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 7: Fix browser validation issues
  {
    name: "Fix browser validation issues",
    description: "Browser testing fails, issues fixed, passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.browserTestingRequired,
      // First attempt: browser validation fails
      "validate-browser-functionality": [
        inputs.browserValidationFailed,
        inputs.browserValidationPassed,
      ],
      "fix-broken-functionality-action": inputs.functionalityFixed,
      "document-functionality-fixes": inputs.functionalityFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 8: Fix checklist issues
  {
    name: "Fix checklist issues",
    description: "Checklist fails, issues fixed, passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "create-iteration-workspace-checklist": {
        step_results_file: "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
      },
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      // First attempt: checklist fails
      "check-project-checklist": [inputs.checklistFailed, inputs.checklistPassed],
      "fix-checklist-issues": inputs.checklistFixed,
      "document-checklist-fixes": inputs.checklistFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 9: Fix agent validation issues (no plan update)
  {
    name: "Fix agent validation issues",
    description: "Agent review finds issues, fixed without plan update",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      // First attempt: agent validation fails
      "agent-validate-step": [
        inputs.agentValidationFailedNoPlanUpdate,
        inputs.agentValidationPassed,
      ],
      "fix-agent-feedback-issues-action": inputs.fixAgentFeedbackNoPlanUpdate,
      "document-review-fixes": inputs.reviewFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After fix: continue
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 10: Fix documentation issues
  {
    name: "Fix documentation issues",
    description: "Documentation validation fails, fixed, passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.documentationOnlyChanges,
      // Documentation path
      "validate-documentation": [inputs.documentationInvalid, inputs.documentationValid],
      "fix-documentation-issues": inputs.documentationFixed,
      "check-documentation-fixes-complete": inputs.documentationFixesDocumented,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 11: Iteration limit reached - user continues
  // Flow: tests fail 3 times → iteration limit reached → user chooses continue → reset counter → fix succeeds → complete
  {
    name: "Iteration limit - continue",
    description: "Fix iteration limit reached, user chooses to continue, counter reset",
    expect: { status: "completed", maxSteps: 250 },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      // 11 iterations: 10 failures (to reach limit) + 1 success after reset
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-4/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-5/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-6/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-7/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-8/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-9/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-10/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-11/step-results.md",
        },
      ],
      "restart-and-rebuild": [
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
      ],
      "analyze-implementation-changes": [
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
      ],
      "analyze-code-changes": [
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
      ],
      // Full path for code changes before tests (11 iterations)
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "verify-functionality-manually": [
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
      ],
      "check-code-quality-and-architecture": [
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
      ],
      "check-browser-impact": [
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
      ],
      "assess-testing-needs": [
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
      ],
      // Tests fail 10 times, then pass after counter reset
      "run-all-tests": [
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.allTestsPass,
      ],
      "analyze-test-failures": [
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
      ],
      "fix-implementation-for-tests-action": [
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
      ],
      "document-test-fixes": [
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
      ],
      // After 10th failure, iteration limit reached → escalate → user continues
      "escalate-iteration-limit": inputs.escalationContinue,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After counter reset, 11th iteration succeeds
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 12: Iteration limit reached - user aborts
  // Flow: tests fail 3 times → iteration limit reached → user chooses abort → document abort state → end
  {
    name: "Iteration limit - abort",
    description: "Fix iteration limit reached, user chooses to abort development",
    expect: { status: "completed", maxSteps: 250 },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      // 10 iterations until limit
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-2/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-3/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-4/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-5/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-6/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-7/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-8/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-9/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-1/iteration-10/step-results.md",
        },
      ],
      "restart-and-rebuild": [
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
        inputs.startupSuccess,
      ],
      "analyze-implementation-changes": [
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
        inputs.codeChanges,
      ],
      "analyze-code-changes": [
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
        inputs.codeAnalysisWithFunctions,
      ],
      // Full path for code changes before tests
      "check-implementation-completeness": [
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
        inputs.implementationComplete,
      ],
      "verify-functionality-manually": [
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
        inputs.allFunctionsWorking,
      ],
      "check-code-quality-and-architecture": [
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
        inputs.qualityCheckPassed,
      ],
      "check-browser-impact": [
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
        inputs.noBrowserTesting,
      ],
      "assess-testing-needs": [
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
        inputs.noNewTestsRequired,
      ],
      // Tests fail all 10 times
      "run-all-tests": [
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
      ],
      "analyze-test-failures": [
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
        inputs.testFailureFixCode,
      ],
      "fix-implementation-for-tests-action": [
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
        inputs.testsFixedByCode,
      ],
      "document-test-fixes": [
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
        inputs.testFixesDocumented,
      ],
      // After 10th failure, iteration limit reached → escalate → user aborts
      "escalate-iteration-limit": inputs.escalationAbort,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // Abort flow → document abort state → end (no inputSchema, empty input)
      "document-abort-state": {},
    },
  },

  // Scenario 13: Test update iteration limit reached via update_tests path
  // Flow: tests fail 10 times with update_tests strategy → check-test-update-limit triggers → escalate → continue
  {
    name: "Test update iteration limit reached",
    description: "Test update loop hits limit via update_tests fix_strategy path",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "check-implementation-completeness": inputs.implementationComplete,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      // Tests fail 10 times via update_tests path, then pass after escalation reset
      "run-all-tests": [
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.someTestsFail,
        inputs.allTestsPass,
      ],
      "analyze-test-failures": [
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
        inputs.testFailureUpdateTests,
      ],
      "update-tests-for-changes": [
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
        inputs.testsUpdated,
      ],
      // After 10th test update, check-test-update-limit triggers → escalate → user continues
      "escalate-iteration-limit": inputs.escalationContinue,
      "read-prior-iteration-results": inputs.priorIterationResultsRead,
      // After counter reset, 11th iteration succeeds
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },
];
