/**
 * Happy Path Scenarios for software-development-flow
 *
 * Tests complete development flows where everything succeeds on first try.
 */

import type { TestScenario } from "../../../helpers/scenario-runner.js";
import * as inputs from "./base-inputs.js";

export const happyPathScenarios: TestScenario[] = [
  // Scenario 1: Full development with 3 steps, all validations pass
  {
    name: "Full development happy path",
    description: "Complete 3-step development with all checks passing",
    expect: { status: "completed" },
    mockInputs: {
      // Phase 1: Project study
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,

      // Phase 2: Planning
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.standardPlanTracking,

      // Phase 3: Initial startup
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,

      // Step 1 execution
      "create-initial-iteration-workspace": [
        inputs.standardInitialIterationWorkspace,
        inputs.standardInitialIterationWorkspace,
        inputs.standardInitialIterationWorkspace,
      ],
      "implement-step": [
        inputs.standardImplementation,
        { implemented_functionality: "Implemented login endpoint" },
        { implemented_functionality: "Added unit tests" },
      ],
      "create-iteration-workspace": [
        inputs.standardIterationWorkspace,
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-2/iteration-1/step-results.md",
        },
        {
          step_results_file:
            "./moira-ws/user-auth-20251225-1200/step-3/iteration-1/step-results.md",
        },
      ],
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "get-next-step-name": [
        { current_step_name: "Implement login" },
        { current_step_name: "Add tests" },
      ],

      // Completion
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 2: Single step development (minimal path)
  {
    name: "Single step development",
    description: "Minimal development with one step",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": {
        ...inputs.standardPlan,
      },
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 3: Development with user approval required
  {
    name: "Development with user approval",
    description: "Step requires user approval which is granted",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNeeded,
      "user-review-step": inputs.userStepApproved,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 4: Development with browser UI testing
  {
    name: "Development with browser testing",
    description: "Changes require browser validation which passes",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      "run-all-tests": inputs.allTestsPass,
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.browserTestingRequired,
      "validate-browser-functionality": inputs.browserValidationPassed,
      "assess-testing-needs": inputs.noNewTestsRequired,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },

  // Scenario 5: Development with new tests required
  {
    name: "Development with new tests",
    description: "New functionality requires new tests to be written",
    expect: { status: "completed" },
    mockInputs: {
      ...inputs.standardPipeline,
      "get-task-requirements": inputs.standardTaskRequirements,
      "study-project-foundation": inputs.standardProjectFoundation,
      "study-implementation-details": inputs.standardImplementationDetails,
      "create-feature-workspace": inputs.standardFeatureWorkspace,
      "present-requirements-confirmation": inputs.requirementsConfirmed,
      "ask-screenshot-validation": inputs.screenshotValidationDisabled,
      "analyze-and-plan": inputs.standardPlan,
      "agent-review-plan": inputs.planReviewNoIssues,
      "present-plan-to-user": inputs.planApproved,
      "initialize-plan-tracking": inputs.singleStepPlanTracking,
      "initial-system-startup": inputs.initialSystemStartup,
      "initial-run-tests": inputs.initialTestsRun,
      "create-initial-iteration-workspace": inputs.standardInitialIterationWorkspace,
      "implement-step": inputs.standardImplementation,
      "create-iteration-workspace": inputs.standardIterationWorkspace,
      "restart-and-rebuild": inputs.startupSuccess,
      "analyze-implementation-changes": inputs.codeChanges,
      "analyze-code-changes": inputs.codeAnalysisWithFunctions,
      "verify-functionality-manually": inputs.allFunctionsWorking,
      // First run before assess-testing-needs, second run after writing new tests
      "run-all-tests": [inputs.allTestsPass, inputs.allTestsPass],
      "check-implementation-completeness": inputs.implementationComplete,
      "check-code-quality-and-architecture": inputs.qualityCheckPassed,
      "check-browser-impact": inputs.noBrowserTesting,
      // First call: tests needed, second call (after writing tests): tests now covered
      "assess-testing-needs": [inputs.newTestsRequired, inputs.noNewTestsRequired],
      "write-new-tests-action": inputs.newTestsWritten,
      "document-new-tests": inputs.newTestsDocumented,
      "update-step-documentation": inputs.stepDocumentationUpdated,
      "check-project-checklist": inputs.checklistPassed,
      "agent-validate-step": inputs.agentValidationPassed,
      "commit-step": inputs.commitStep,
      "check-user-approval-needed": inputs.userApprovalNotNeeded,
      "validate-requirements-coverage": inputs.requirementsCoverageValid,
      "generate-final-report": inputs.finalReportGenerated,
      "present-results": inputs.userPermissionGranted,
      "collect-user-feedback": inputs.userSatisfied,
      "update-documentation": inputs.finalDocumentationUpdate,
    },
  },
];
