/**
 * Generates the process-view prototype's workflow snapshot from the bundled flow files.
 *
 * The frontend cannot read `workflows/production/flows/` at runtime and the API serves the
 * version-gated catalog copy, so the prototype renders a checked-in snapshot instead. Run this after
 * annotating a flow (progressNodeId, progress.nodes, connectionLabels) to refresh it:
 *
 *   npm run prototype:snapshot
 *
 * Output: packages/web-frontend/src/prototypes/process-view/fixtures/authored.ts (authored nodes,
 * exported under the names the hand-written fixtures import) and fixtures/workflows.ts (the annotated
 * workflow surface the derivation reads).
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface Source {
  file: string;
  slug: string;
  exportName: string;
}

const ROOT = resolve(import.meta.dirname, "..");
const OUT_DIR = resolve(ROOT, "packages/web-frontend/src/prototypes/process-view/fixtures");
const SOURCES: Source[] = [
  {
    file: "workflows/production/flows/e21e3890-daf3-44b9-8143-9fa8be1b9231.json",
    slug: "quick-task",
    exportName: "QUICK_TASK",
  },
  {
    file: "workflows/production/flows/91b11263-a180-4a08-9399-55f406f82c69.json",
    slug: "software-development-flow",
    exportName: "SDF",
  },
];

/** First sentence of the agent-facing text, bounded; empty for routing nodes. */
function summaryOf(node: Record<string, unknown>): string {
  const text =
    (typeof node.directive === "string" && node.directive) ||
    (typeof node.message === "string" && node.message) ||
    (typeof node.hint === "string" && node.hint) ||
    "";
  const firstSentence = text.split(/(?<=[.!?])\s/)[0]?.trim() ?? "";
  return firstSentence.length > 160 ? `${firstSentence.slice(0, 157)}…` : firstSentence;
}

const literal = (value: unknown): string => JSON.stringify(value, null, 2);

/** Names of the fields a step must return: its inputSchema properties plus the globals it writes. */
function inputsOf(node: Record<string, unknown>): string[] {
  const schema = node.inputSchema as
    { properties?: Record<string, unknown>; globalInputs?: string[] } | undefined;
  return [...new Set([...Object.keys(schema?.properties ?? {}), ...(schema?.globalInputs ?? [])])];
}

/** `progress.title` may be a template ("plan r{{plan_revision}}"); the snapshot has no run to resolve it. */
function plainTitle(workflow: {
  progress?: { title?: string };
  metadata: { name: string };
}): string {
  const title = workflow.progress?.title;
  return title && !title.includes("{{") ? title : workflow.metadata.name;
}

let authoredOut = `/**
 * Authored-node snapshots of bundled workflows. GENERATED by scripts/generate-process-view-snapshot.ts
 * from workflows/production/flows/ — do not edit by hand; rerun \`npm run prototype:snapshot\`.
 * Prototype fixture data for the aggregated process view; not a runtime contract.
 */
import type { AuthoredNode } from "../model";
`;
let workflowsOut = `/**
 * Annotated workflow surfaces the derivation reads. GENERATED by
 * scripts/generate-process-view-snapshot.ts from workflows/production/flows/ — do not edit by hand;
 * rerun \`npm run prototype:snapshot\`.
 */
import type { AnnotatedWorkflow } from "../model";
`;

for (const source of SOURCES) {
  const workflow = JSON.parse(readFileSync(resolve(ROOT, source.file), "utf8"));
  const nodes = (workflow.nodes as Array<Record<string, unknown>>).map((node) => ({
    id: node.id,
    type: node.type,
    summary: summaryOf(node),
    connections: node.connections ?? {},
    ...(node.connectionLabels ? { connectionLabels: node.connectionLabels } : {}),
    ...(node.condition ? { condition: node.condition } : {}),
    ...(Array.isArray(node.expressions) ? { expressions: node.expressions } : {}),
    ...(inputsOf(node).length ? { inputs: inputsOf(node) } : {}),
    progressNodeId: node.progressNodeId ?? null,
  }));
  const progressNodes = (workflow.progress?.nodes ?? []) as Array<Record<string, unknown>>;
  const blocks = progressNodes.map((block) => {
    const content = (block.content ?? {}) as Record<string, unknown>;
    return {
      id: block.id,
      label: block.label,
      summary: typeof content.summary === "string" ? content.summary : "",
      ...(typeof content.outcome === "string" ? { outcome: content.outcome } : {}),
      ...(typeof content.next === "string" ? { next: content.next } : {}),
      ...((block.connections as { default?: string } | undefined)?.default
        ? { next_block: (block.connections as { default: string }).default }
        : {}),
    };
  });
  const authoredName = `${source.exportName}_AUTHORED`;
  authoredOut += `
/** ${workflow.metadata.name} — ${nodes.length} authored nodes, workflow version ${workflow.metadata.version}. */
export const ${authoredName}: AuthoredNode[] = ${literal(nodes)};
`;
  workflowsOut += `
export const ${source.exportName}_WORKFLOW: AnnotatedWorkflow = {
  slug: ${literal(source.slug)},
  title: ${literal(plainTitle(workflow))},
  goal: ${literal(workflow.progress?.goal ?? workflow.metadata.description ?? "")},
  version: ${literal(workflow.metadata.version)},
  blocks: ${literal(blocks)},
  nodeCount: ${nodes.length},
};
`;
}

writeFileSync(resolve(OUT_DIR, "authored.ts"), authoredOut);
writeFileSync(resolve(OUT_DIR, "workflows.ts"), workflowsOut);
execSync(
  `npx prettier --write "${resolve(OUT_DIR, "authored.ts")}" "${resolve(OUT_DIR, "workflows.ts")}"`,
  {
    stdio: "ignore",
  },
);
console.log(`Snapshot written for ${SOURCES.map((s) => s.slug).join(", ")} → ${OUT_DIR}`);
