import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  computeToolContractRevision,
  renderToolReference,
} from "../packages/mcp-server/src/tools/tool-definitions.js";

export function getGeneratedMcpContractFiles(projectRoot: string): ReadonlyMap<string, string> {
  return new Map([
    [
      resolve(projectRoot, "packages/shared/src/config/mcp-tools-revision.generated.ts"),
      `/** Generated by scripts/generate-mcp-contracts.ts. Do not edit manually. */\nexport const MCP_TOOLS_REVISION = "${computeToolContractRevision()}";\n`,
    ],
    [
      resolve(projectRoot, "packages/docs/src/fragments/mcp-tools.en.md"),
      `<!-- Generated by scripts/generate-mcp-contracts.ts. Do not edit manually. -->\n\n${renderToolReference("en", 2)}`,
    ],
    [
      resolve(projectRoot, "packages/docs/src/fragments/mcp-tools.ru.md"),
      `<!-- Generated by scripts/generate-mcp-contracts.ts. Do not edit manually. -->\n\n${renderToolReference("ru", 2)}`,
    ],
  ]);
}

export function generateMcpContracts(projectRoot: string, check: boolean): void {
  const generatedFiles = getGeneratedMcpContractFiles(projectRoot);
  if (check) {
    const stale = [...generatedFiles].filter(([filePath, expected]) => {
      try {
        return readFileSync(filePath, "utf8") !== expected;
      } catch {
        return true;
      }
    });
    if (stale.length > 0) {
      throw new Error(
        `Generated MCP contract output is stale: ${stale.map(([filePath]) => filePath).join(", ")}. Run npm run generate:mcp-contracts.`,
      );
    }
    return;
  }

  for (const [filePath, content] of generatedFiles) {
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, content);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateMcpContracts(process.cwd(), process.argv.includes("--check"));
}
