#!/usr/bin/env node
/**
 * Unified Migration Runner
 * Runs Drizzle migrations + custom seeding logic
 */

import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import Database from "better-sqlite3";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import "dotenv/config";
import {
  createAuth,
  createLogger,
  Service,
  setGlobalService,
  loadPersistedSecrets,
} from "@mcp-moira/shared";

// Pick up self-host secrets generated by bootstrap-secrets.ts (e.g. ADMIN_PASSWORD)
// before they are read below. No-op when the file is absent (saas / explicit env).
loadPersistedSecrets();

// Set global service for this script process
setGlobalService(Service.WEB_BACKEND);

const logger = createLogger({ component: "Migration" });
const auth = createAuth(logger);

const dbPath = path.resolve(process.env.DB_PATH || "./data/moira.db");
const migrationsFolder = path.resolve("./packages/web-backend/drizzle");

console.log("Running unified migrations...");
console.log("Database:", dbPath);
console.log("Migrations:", migrationsFolder);
console.log("");

// Create database connection
const sqlite = new Database(dbPath);
sqlite.pragma("foreign_keys = ON");

const db = drizzle(sqlite);

// Pre-migration fixes for SQLite limitations
// Handle migration 0002 which has both CREATE TABLE and ALTER TABLE
// If protected column already exists, migration will fail on ALTER TABLE
// Solution: pre-create tables and mark migration as applied
console.log("🔧 Pre-migration fixes for SQLite limitations...");

// Check if migration 0002 needs special handling
const settingDefCols = sqlite.prepare("PRAGMA table_info(settingDefinition)").all() as Array<{
  name: string;
}>;
const protectedExists = settingDefCols.some((col) => col.name === "protected");

// Check if note tables exist
const noteTableExists = sqlite
  .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='note'")
  .get();

if (protectedExists && !noteTableExists) {
  console.log("  ⚠️  Detected: protected column exists but note tables missing");
  console.log("  ⚠️  This means migration 0002 partially failed. Fixing...");

  // Create note table
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS "note" (
      "id" text PRIMARY KEY NOT NULL,
      "userId" text NOT NULL,
      "key" text NOT NULL,
      "tags" text,
      "size" integer DEFAULT 0 NOT NULL,
      "currentVersion" integer DEFAULT 1 NOT NULL,
      "deleted" integer DEFAULT false,
      "deletedAt" integer,
      "deletedBy" text,
      "createdAt" integer NOT NULL,
      "updatedAt" integer NOT NULL,
      FOREIGN KEY ("userId") REFERENCES "user"("id") ON UPDATE no action ON DELETE cascade,
      FOREIGN KEY ("deletedBy") REFERENCES "user"("id") ON UPDATE no action ON DELETE no action
    );
  `);
  console.log("  ✅ Created note table");

  sqlite.exec(`CREATE UNIQUE INDEX IF NOT EXISTS "note_user_key_idx" ON "note" ("userId","key");`);
  console.log("  ✅ Created note_user_key_idx");

  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS "noteVersion" (
      "id" text PRIMARY KEY NOT NULL,
      "noteId" text NOT NULL,
      "version" integer NOT NULL,
      "value" text NOT NULL,
      "size" integer NOT NULL,
      "createdAt" integer NOT NULL,
      FOREIGN KEY ("noteId") REFERENCES "note"("id") ON UPDATE no action ON DELETE cascade
    );
  `);
  console.log("  ✅ Created noteVersion table");

  sqlite.exec(
    `CREATE UNIQUE INDEX IF NOT EXISTS "note_version_idx" ON "noteVersion" ("noteId","version");`,
  );
  console.log("  ✅ Created note_version_idx");

  // Check if migration 0002 is already recorded
  const migration0002 = sqlite
    .prepare("SELECT * FROM __drizzle_migrations WHERE created_at = 1769271231107")
    .get();

  if (!migration0002) {
    // Mark migration 0002 as applied
    // The hash needs to match what Drizzle expects - generate from migration file
    const migrationHash = crypto
      .createHash("sha256")
      .update(fs.readFileSync(path.join(migrationsFolder, "0002_vengeful_tigra.sql"), "utf-8"))
      .digest("hex");

    sqlite
      .prepare("INSERT INTO __drizzle_migrations (hash, created_at) VALUES (?, ?)")
      .run(migrationHash, 1769271231107);
    console.log("  ✅ Marked migration 0002 as applied");
  }
}

console.log("");

// Run Drizzle migrations
console.log("✅ Running Drizzle schema migrations...");
migrate(db, { migrationsFolder });
console.log("✅ Schema migrations complete");
console.log("");

// Post-migration fixes for SQLite limitations (ALTER TABLE IF NOT EXISTS not supported)
console.log("🔧 Post-migration fixes...");

// Add auditLog.changes if not exists (migration 0011 workaround)
const auditLogColumns = sqlite.prepare("PRAGMA table_info(auditLog)").all() as Array<{
  name: string;
}>;
if (auditLogColumns.length > 0 && !auditLogColumns.some((col) => col.name === "changes")) {
  sqlite.prepare("ALTER TABLE auditLog ADD COLUMN changes TEXT").run();
  console.log("  ✅ Added auditLog.changes column");
} else {
  console.log("  ⏭️  auditLog.changes column already exists");
}

// Add auditLog.source if not exists (observability-improvements Stage 2)
if (auditLogColumns.length > 0 && !auditLogColumns.some((col) => col.name === "source")) {
  sqlite.prepare("ALTER TABLE auditLog ADD COLUMN source TEXT").run();
  console.log("  ✅ Added auditLog.source column");
} else {
  console.log("  ⏭️  auditLog.source column already exists");
}

// Add GDPR consent columns if not exist (migration 0017 workaround)
const userColumns = sqlite.prepare("PRAGMA table_info(user)").all() as Array<{ name: string }>;
if (userColumns.length > 0 && !userColumns.some((col) => col.name === "acceptedTermsAt")) {
  sqlite.prepare("ALTER TABLE user ADD COLUMN acceptedTermsAt TEXT").run();
  console.log("  ✅ Added user.acceptedTermsAt column");
} else {
  console.log("  ⏭️  user.acceptedTermsAt column already exists");
}
if (
  userColumns.length > 0 &&
  !userColumns.some((col) => col.name === "acceptedNotRussianResidentAt")
) {
  sqlite.prepare("ALTER TABLE user ADD COLUMN acceptedNotRussianResidentAt TEXT").run();
  console.log("  ✅ Added user.acceptedNotRussianResidentAt column");
} else {
  console.log("  ⏭️  user.acceptedNotRussianResidentAt column already exists");
}

// NOTE: oauthAccessToken.toolsVersion is added via Drizzle migration 0018_add_tools_version.sql
// No post-migration fix needed here

// Add settingDefinition.protected if not exists
const settingDefColumns = sqlite.prepare("PRAGMA table_info(settingDefinition)").all() as Array<{
  name: string;
}>;
if (settingDefColumns.length > 0 && !settingDefColumns.some((col) => col.name === "protected")) {
  sqlite.prepare("ALTER TABLE settingDefinition ADD COLUMN protected INTEGER DEFAULT 0").run();
  console.log("  ✅ Added settingDefinition.protected column");
} else {
  console.log("  ⏭️  settingDefinition.protected column already exists");
}

// Mark critical setting definitions as protected
const protectedKeys = [
  "telegram.bot_token",
  "telegram.chat_id",
  "telegram.enabled",
  "mcp.systemReminder",
];
for (const key of protectedKeys) {
  const result = sqlite
    .prepare(
      "UPDATE settingDefinition SET protected = 1 WHERE key = ? AND (protected IS NULL OR protected = 0)",
    )
    .run(key);
  if (result.changes > 0) {
    console.log(`  ✅ Marked ${key} as protected`);
  }
}

// Migrate telegram settings category from "telegram" to "notifications" (flatten subgroup)
const telegramCategoryResult = sqlite
  .prepare("UPDATE settingDefinition SET category = 'notifications' WHERE category = 'telegram'")
  .run();
if (telegramCategoryResult.changes > 0) {
  console.log(
    `  ✅ Migrated ${telegramCategoryResult.changes} telegram settings to 'notifications' category`,
  );
} else {
  console.log("  ⏭️  Telegram settings already in 'notifications' category");
}

// Add validation cache columns if not exist (Issue #463 - workflow list performance)
const workflowColumns = sqlite.prepare("PRAGMA table_info(workflow)").all() as Array<{
  name: string;
}>;
if (workflowColumns.length > 0 && !workflowColumns.some((col) => col.name === "isValid")) {
  sqlite.prepare("ALTER TABLE workflow ADD COLUMN isValid INTEGER").run();
  console.log("  ✅ Added workflow.isValid column");
} else {
  console.log("  ⏭️  workflow.isValid column already exists");
}
if (workflowColumns.length > 0 && !workflowColumns.some((col) => col.name === "validationErrors")) {
  sqlite.prepare("ALTER TABLE workflow ADD COLUMN validationErrors TEXT").run();
  console.log("  ✅ Added workflow.validationErrors column");
} else {
  console.log("  ⏭️  workflow.validationErrors column already exists");
}
if (workflowColumns.length > 0 && !workflowColumns.some((col) => col.name === "validatedAt")) {
  sqlite.prepare("ALTER TABLE workflow ADD COLUMN validatedAt INTEGER").run();
  console.log("  ✅ Added workflow.validatedAt column");
} else {
  console.log("  ⏭️  workflow.validatedAt column already exists");
}

// Artifact abuse controls (migration 0011 workaround for existing DBs)
const artifactColumns = sqlite.prepare("PRAGMA table_info(artifact)").all() as Array<{
  name: string;
}>;
if (artifactColumns.length > 0) {
  const artifactAbuseColumns: Array<{ name: string; ddl: string }> = [
    {
      name: "reportCount",
      ddl: "ALTER TABLE artifact ADD COLUMN reportCount INTEGER DEFAULT 0 NOT NULL",
    },
    { name: "lastReportedAt", ddl: "ALTER TABLE artifact ADD COLUMN lastReportedAt INTEGER" },
    {
      name: "takenDown",
      ddl: "ALTER TABLE artifact ADD COLUMN takenDown INTEGER DEFAULT 0 NOT NULL",
    },
    { name: "takenDownAt", ddl: "ALTER TABLE artifact ADD COLUMN takenDownAt INTEGER" },
    { name: "takenDownBy", ddl: "ALTER TABLE artifact ADD COLUMN takenDownBy TEXT" },
    { name: "takenDownReason", ddl: "ALTER TABLE artifact ADD COLUMN takenDownReason TEXT" },
  ];
  for (const col of artifactAbuseColumns) {
    if (!artifactColumns.some((c) => c.name === col.name)) {
      sqlite.prepare(col.ddl).run();
      console.log(`  ✅ Added artifact.${col.name} column`);
    } else {
      console.log(`  ⏭️  artifact.${col.name} column already exists`);
    }
  }
}

// Issue #386: Execution Error Log - Data Migration
// Migrate status: waiting → running, failed → completed
// Migrate error field to errors array
console.log("");
console.log("🔄 Issue #386: Execution status and error migration...");

// 1. Migrate waiting → running
const waitingResult = sqlite
  .prepare("UPDATE workflowExecution SET state = 'running' WHERE state = 'waiting'")
  .run();
if (waitingResult.changes > 0) {
  console.log(`  ✅ Migrated ${waitingResult.changes} executions: waiting → running`);
} else {
  console.log("  ⏭️  No 'waiting' executions to migrate");
}

// 2. Migrate failed → completed
const failedResult = sqlite
  .prepare("UPDATE workflowExecution SET state = 'completed' WHERE state = 'failed'")
  .run();
if (failedResult.changes > 0) {
  console.log(`  ✅ Migrated ${failedResult.changes} executions: failed → completed`);
} else {
  console.log("  ⏭️  No 'failed' executions to migrate");
}

// 3. Migrate error field to errors array (only if error exists and errors is empty/null)
interface ExecutionWithError {
  executionId: string;
  error: string;
  currentNodeId: string | null;
  updatedAt: number | null;
}
const executionsWithError = sqlite
  .prepare(
    `SELECT executionId, error, currentNodeId, updatedAt
     FROM workflowExecution
     WHERE error IS NOT NULL AND error != ''
     AND (errors IS NULL OR errors = '[]' OR errors = '')`,
  )
  .all() as ExecutionWithError[];

if (executionsWithError.length > 0) {
  const updateStmt = sqlite.prepare(
    "UPDATE workflowExecution SET errors = ? WHERE executionId = ?",
  );

  for (const exec of executionsWithError) {
    // Create ExecutionError entry from legacy error field
    const errorEntry = {
      timestamp: exec.updatedAt || Date.now(),
      nodeId: exec.currentNodeId || "unknown",
      errorType: "system" as const,
      message: exec.error,
    };
    const errorsArray = JSON.stringify([errorEntry]);
    updateStmt.run(errorsArray, exec.executionId);
  }
  console.log(`  ✅ Migrated ${executionsWithError.length} error fields to errors array`);
} else {
  console.log("  ⏭️  No legacy error fields to migrate");
}

// Seed admin user if ADMIN_PASSWORD provided
const adminEmail = process.env.ADMIN_EMAIL || "admin@moira.local";
const adminPassword = process.env.ADMIN_PASSWORD;
const deploymentMode = (process.env.DEPLOYMENT_MODE || "self-host").trim().toLowerCase();

if (!adminPassword) {
  if (deploymentMode === "saas") {
    // saas: an admin password must be supplied explicitly.
    console.error("");
    console.error(
      "❌ ERROR: ADMIN_PASSWORD environment variable is required (DEPLOYMENT_MODE=saas)",
    );
    console.error("   Set ADMIN_PASSWORD in your environment before deployment");
    console.error("");
    process.exit(1);
  }
  // self-host: bootstrap-secrets.ts generates ADMIN_PASSWORD before this runs.
  // If it is still absent (e.g. bootstrap skipped), skip admin seeding instead
  // of aborting startup — the rest of the system must come up regardless.
  console.log("⏭️  Skipping admin user creation (ADMIN_PASSWORD not set, self-host)");
}

if (adminPassword) {
  console.log("📝 Seeding admin user...");

  const adminId = "system-admin";

  // Check if admin already exists
  const existingUser = sqlite.prepare("SELECT id FROM user WHERE id = ?").get(adminId);

  if (!existingUser) {
    // Admin user always gets handle "admin"
    const adminHandle = "admin";
    sqlite
      .prepare(
        `
      INSERT INTO user (id, email, name, handle, emailVerified, isAdmin, createdAt, updatedAt)
      VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
    `,
      )
      .run(adminId, adminEmail, "Admin User", adminHandle, 1, 1);

    console.log("  ✅ Admin user created with admin flag");
  } else {
    // Update existing admin user to set isAdmin flag
    sqlite.prepare("UPDATE user SET isAdmin = 1 WHERE id = ?").run(adminId);
    console.log("  ✅ Admin user updated with admin flag");
  }

  // Create or update admin account with password
  // Delete all existing credential accounts to avoid duplicates
  sqlite
    .prepare("DELETE FROM account WHERE userId = ? AND providerId = ?")
    .run(adminId, "credential");

  // Hash password using Better Auth API (ensures correct format)
  const ctx = await auth.$context;
  const hashedPassword = await ctx.password.hash(adminPassword);

  sqlite
    .prepare(
      `
    INSERT INTO account (id, userId, accountId, providerId, password, createdAt, updatedAt)
    VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now'))
  `,
    )
    .run(crypto.randomUUID(), adminId, adminEmail, "credential", hashedPassword);

  console.log("  ✅ Admin account created with Better Auth password hash");

  console.log("");
  console.log("Admin user seeded:");
  console.log("  Email:", adminEmail);
  console.log("  User ID:", adminId);
  // Password is intentionally NOT printed here. For self-host generation it is
  // shown once by bootstrap-secrets.ts; an operator-supplied password must not
  // be echoed to logs.
}

console.log("");

// Seed Moira system user if not exists
const moiraUserId = "system-moira";
const existingMoiraUser = sqlite.prepare("SELECT id FROM user WHERE id = ?").get(moiraUserId);

if (!existingMoiraUser) {
  console.log("📝 Seeding Moira system user...");

  const moiraEmail = `moira@${process.env.MOIRA_HOST ?? "moira.local"}`;
  const moiraHandle = "moira";

  sqlite
    .prepare(
      `
    INSERT INTO user (id, email, name, handle, createdAt, updatedAt)
    VALUES (?, ?, ?, ?, datetime('now'), datetime('now'))
  `,
    )
    .run(moiraUserId, moiraEmail, "Moira", moiraHandle);
  console.log("  ✅ Moira system user created");
} else {
  console.log("  ⏭️  Moira system user already exists");
}

// Seed setting definitions
console.log("📝 Seeding setting definitions...");
const { seedSettingDefinitions } = await import("./seed-settings-definitions.js");
await seedSettingDefinitions();
console.log("  ✅ Setting definitions seeded");

// Close the main DB connection before prompt migration (which opens its own)
sqlite.close();

// Run prompt migration with hash-based conflict detection
// Replaces: seedMcpTexts(), systemReminder seeding, systemPrompt update
// All prompts are now managed from config/prompts/ with SHA-256 hash protection
const { runPromptMigration } = await import("./prompt-migration.js");
runPromptMigration(dbPath);

console.log("");
console.log("✅ All migrations complete!");
