/**
 * MCP OAuth Authentication Utilities
 * Pure HTTP OAuth flow for E2E testing - NO browser automation
 */

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { getTestBaseUrl, getTestFetchUrl, getAdminCredentials } from "./test-config.js";

/** Thrown when authorize returns invalid_client — signals caller to re-register */
class InvalidClientError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidClientError";
  }
}

/**
 * Get the session cookie name based on the URL protocol.
 * Better Auth uses __Secure- prefix for HTTPS, no prefix for HTTP.
 */
function getSessionCookieName(baseUrl: string): string {
  const isSecure = baseUrl.startsWith("https://");
  return isSecure ? "__Secure-better-auth.session_token" : "better-auth.session_token";
}

/**
 * Format Cookie header with proper cookie name for the protocol.
 */
function formatSessionCookie(baseUrl: string, sessionCookie: string): string {
  return `${getSessionCookieName(baseUrl)}=${sessionCookie}`;
}

/**
 * Extract session cookie from Set-Cookie header.
 * Handles both secure (__Secure-) and non-secure cookie names.
 */
function extractSessionCookie(setCookieHeader: string | null): string | null {
  if (!setCookieHeader) return null;
  // Match both __Secure-better-auth.session_token and better-auth.session_token
  const match = setCookieHeader.match(/(?:__Secure-)?better-auth\.session_token=([^;]+)/);
  return match ? match[1] : null;
}

/**
 * Default admin credentials for testing
 * Uses centralized getAdminCredentials() from test-config
 */
export const DEFAULT_ADMIN_CREDENTIALS = getAdminCredentials();

/**
 * Verify user email via admin API (standalone function for E2E tests)
 *
 * @param baseUrl - Base URL of the application
 * @param userEmail - Email of the user to verify
 * @returns Promise that resolves when email is verified
 *
 * @example
 * await verifyUserEmail(BASE_URL, 'test@example.com');
 */
export async function verifyUserEmail(baseUrl: string, userEmail: string): Promise<void> {
  // Get cached admin session cookie
  const adminSessionCookie = await getAdminSessionCookie(baseUrl);

  // Call the internal verification function
  await verifyUserEmailViaAdmin(baseUrl, userEmail, adminSessionCookie);
}

/**
 * Create test user and optionally verify email via API
 * Pure HTTP, no browser automation
 *
 * @param baseUrl - Base URL of the application
 * @param email - User email
 * @param password - User password
 * @param name - User name
 * @param verifyEmail - Whether to verify email (default: true)
 * @returns User ID if successful
 */
export async function createTestUserViaApi(
  baseUrl: string,
  email: string,
  password: string,
  name: string,
  verifyEmail = true,
): Promise<{ userId: string }> {
  // Sign up user with legal consent (required for GDPR compliance)
  // Note: handle is auto-generated by the server from email prefix
  const signUpResponse = await fetch(`${baseUrl}/api/auth/sign-up/email`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      email,
      password,
      name,
      acceptedTermsAt: new Date().toISOString(),
      acceptedNotRussianResidentAt: new Date().toISOString(),
    }),
  });

  if (!signUpResponse.ok && signUpResponse.status !== 422) {
    throw new Error(`Sign-up failed: ${signUpResponse.status}`);
  }

  // Get cached admin session for subsequent operations
  const adminSessionCookie = await getAdminSessionCookie(baseUrl);

  // Find user ID (use search param to find by email in paginated results)
  const usersResponse = await fetch(
    `${baseUrl}/api/admin/users?search=${encodeURIComponent(email)}&limit=10`,
    {
      headers: {
        Cookie: formatSessionCookie(baseUrl, adminSessionCookie),
      },
    },
  );

  if (!usersResponse.ok) {
    throw new Error(`Failed to get users list: ${usersResponse.status}`);
  }

  const usersData = (await usersResponse.json()) as {
    data: { users: Array<{ id: string; email: string }> };
  };
  const user = usersData.data?.users?.find((u) => u.email === email);

  if (!user) {
    throw new Error(`User not found after sign-up: ${email}`);
  }

  // Verify email if requested
  if (verifyEmail) {
    await verifyUserEmailViaAdmin(baseUrl, email, adminSessionCookie);
  }

  return { userId: user.id };
}

/**
 * Block user via admin API
 * Pure HTTP, no browser automation
 *
 * @param baseUrl - Base URL of the application
 * @param userId - User ID to block
 * @param reason - Block reason (optional)
 */
export async function blockUserViaApi(
  baseUrl: string,
  userId: string,
  reason?: string,
): Promise<void> {
  const adminSessionCookie = await getAdminSessionCookie(baseUrl);

  const response = await fetch(`${baseUrl}/api/admin/users/${userId}/block`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Cookie: formatSessionCookie(baseUrl, adminSessionCookie),
    },
    body: JSON.stringify({ reason: reason || "E2E test block" }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to block user: ${response.status} ${error}`);
  }
}

/**
 * Unblock user via admin API
 * Pure HTTP, no browser automation
 *
 * @param baseUrl - Base URL of the application
 * @param userId - User ID to unblock
 */
export async function unblockUserViaApi(baseUrl: string, userId: string): Promise<void> {
  const adminSessionCookie = await getAdminSessionCookie(baseUrl);

  const response = await fetch(`${baseUrl}/api/admin/users/${userId}/unblock`, {
    method: "POST",
    headers: {
      Cookie: formatSessionCookie(baseUrl, adminSessionCookie),
    },
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to unblock user: ${response.status} ${error}`);
  }
}

/**
 * Force password reset via admin API
 * Pure HTTP, no browser automation
 *
 * @param baseUrl - Base URL of the application
 * @param userId - User ID to force password reset
 */
export async function forcePasswordResetViaApi(baseUrl: string, userId: string): Promise<void> {
  const adminSessionCookie = await getAdminSessionCookie(baseUrl);

  const response = await fetch(`${baseUrl}/api/admin/users/${userId}/force-password-reset`, {
    method: "POST",
    headers: {
      Cookie: formatSessionCookie(baseUrl, adminSessionCookie),
    },
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to force password reset: ${response.status} ${error}`);
  }
}

/**
 * Get admin session cookie
 * Useful when you need to make multiple admin API calls
 */
export async function getAdminSessionCookie(baseUrl: string): Promise<string> {
  return signInUser(baseUrl, DEFAULT_ADMIN_CREDENTIALS.email, DEFAULT_ADMIN_CREDENTIALS.password);
}

/**
 * OAuth redirect configuration
 */
const OAUTH_REDIRECT_PORT = 3333;
const OAUTH_REDIRECT_URI = `http://localhost:${OAUTH_REDIRECT_PORT}/oauth/callback`;

interface OAuthClientData {
  client_id: string;
  client_secret: string;
  redirect_uris: string[];
}

interface MCPTestClient {
  client: Client;
  transport: StreamableHTTPClientTransport;
  accessToken: string;
  cleanup: () => Promise<void>;
}

interface CreateMCPClientOptions {
  email: string;
  password: string;
  verifyEmail?: boolean;
  adminCredentials?: { email: string; password: string };
}

/**
 * Register OAuth client with MCP server
 */
async function registerOAuthClient(baseUrl: string): Promise<OAuthClientData> {
  console.log("[OAuth] Step 1: Registering client...");
  const response = await fetch(`${baseUrl}/api/auth/mcp/register`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      client_name: "test-mcp-client-" + Date.now(),
      redirect_uris: [OAUTH_REDIRECT_URI],
      grant_types: ["authorization_code"],
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    console.error("[OAuth] Registration failed:", response.status, error);
    throw new Error(`OAuth client registration failed: ${response.status}`);
  }

  const data = (await response.json()) as OAuthClientData;
  console.log("[OAuth] ✓ Client registered:", data.client_id);
  return data;
}

/**
 * Sign in user and get session cookie
 * @param baseUrl - Base URL of the application
 * @param email - User email
 * @param password - User password
 * @returns Session cookie value
 */
export async function signInUser(
  baseUrl: string,
  email: string,
  password: string,
): Promise<string> {
  console.log("[OAuth] Step 2: Signing in:", email);
  const response = await fetch(`${baseUrl}/api/auth/sign-in/email`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      email,
      password,
      rememberMe: true,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    console.error("[OAuth] Sign in failed:", response.status, error);
    throw new Error(`Sign in failed: ${response.status}`);
  }

  // Extract session cookie from Set-Cookie header
  const setCookieHeader = response.headers.get("set-cookie");
  console.log("[OAuth] Set-Cookie:", setCookieHeader ? "present" : "MISSING");

  const sessionCookie = extractSessionCookie(setCookieHeader);

  if (!sessionCookie) {
    console.error("[OAuth] Session cookie not found in header");
    throw new Error("No session cookie in sign-in response");
  }

  console.log("[OAuth] ✓ Session cookie extracted");
  return sessionCookie;
}

/**
 * Verify user email via admin API
 * Requires admin session to call the admin endpoint
 */
async function verifyUserEmailViaAdmin(
  baseUrl: string,
  userEmail: string,
  adminSessionCookie: string,
): Promise<void> {
  console.log("[OAuth] Verifying email for:", userEmail);

  // Get all users to find the user ID (use search param for paginated results)
  const usersResponse = await fetch(
    `${baseUrl}/api/admin/users?search=${encodeURIComponent(userEmail)}&limit=10`,
    {
      headers: {
        Cookie: formatSessionCookie(baseUrl, adminSessionCookie),
      },
    },
  );

  if (!usersResponse.ok) {
    throw new Error(`Failed to get users list: ${usersResponse.status}`);
  }

  const usersData = (await usersResponse.json()) as {
    data: { users: Array<{ id: string; email: string }> };
  };
  const user = usersData.data?.users?.find((u) => u.email === userEmail);

  if (!user) {
    throw new Error(`User not found: ${userEmail}`);
  }

  // Call verify-email endpoint
  const verifyResponse = await fetch(`${baseUrl}/api/admin/users/${user.id}/verify-email`, {
    method: "POST",
    headers: {
      Cookie: formatSessionCookie(baseUrl, adminSessionCookie),
    },
  });

  if (!verifyResponse.ok) {
    const error = await verifyResponse.text();
    throw new Error(`Failed to verify email: ${verifyResponse.status} ${error}`);
  }

  console.log("[OAuth] ✓ Email verified for:", userEmail);
}

/**
 * Get authorization code via OAuth authorize endpoint
 */
async function getAuthorizationCode(
  baseUrl: string,
  clientId: string,
  sessionCookie: string,
  maxRetries = 3,
): Promise<string> {
  const authorizeUrl = new URL(`${baseUrl}/api/auth/mcp/authorize`);
  authorizeUrl.searchParams.set("client_id", clientId);
  authorizeUrl.searchParams.set("redirect_uri", OAUTH_REDIRECT_URI);
  authorizeUrl.searchParams.set("response_type", "code");
  authorizeUrl.searchParams.set("state", "test-state");
  authorizeUrl.searchParams.set("scope", "openid email profile");

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    console.log(`[OAuth] Step 3: Getting authorization code (attempt ${attempt}/${maxRetries})...`);

    const response = await fetch(authorizeUrl.toString(), {
      method: "GET",
      headers: {
        Cookie: formatSessionCookie(baseUrl, sessionCookie),
      },
      redirect: "manual",
    });

    console.log("[OAuth] Authorize status:", response.status);

    if (response.status !== 302) {
      const error = await response.text();
      console.error("[OAuth] Expected 302, got:", response.status, error);
      throw new Error(`Expected 302 redirect, got ${response.status}`);
    }

    const location = response.headers.get("location");
    console.log("[OAuth] Redirect location:", location?.substring(0, 100) + "...");

    if (location && location.includes("code=")) {
      const locationUrl = new URL(location, baseUrl);
      const code = locationUrl.searchParams.get("code");
      if (code) {
        console.log("[OAuth] ✓ Got code:", code.substring(0, 20) + "...");
        return code;
      }
    }

    // Detect specific error types from redirect
    if (location && location.includes("error=invalid_client")) {
      // Client registration not visible yet (SQLite WAL timing) — caller must re-register
      throw new InvalidClientError(
        `OAuth client not found (invalid_client). Location: ${location}`,
      );
    }

    // Session not recognized — retry with backoff (concurrent DB writes can delay session visibility)
    if (attempt < maxRetries) {
      const delay = attempt * 500;
      console.warn(
        `[OAuth] No code in redirect (session not recognized), retrying in ${delay}ms...`,
      );
      await new Promise((r) => setTimeout(r, delay));
    } else {
      console.error("[OAuth] No code in redirect after all retries. Location:", location);
      throw new Error(`No authorization code in redirect. Location: ${location}`);
    }
  }

  throw new Error("Unreachable");
}

/**
 * Exchange authorization code for access token
 */
async function exchangeCodeForToken(
  baseUrl: string,
  code: string,
  clientId: string,
  clientSecret: string,
): Promise<string> {
  console.log("[OAuth] Step 4: Exchanging code for token...");
  const response = await fetch(`${baseUrl}/api/auth/mcp/token`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      grant_type: "authorization_code",
      code,
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uri: OAUTH_REDIRECT_URI,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    console.error("[OAuth] Token exchange failed:", response.status, error);
    throw new Error(`Token exchange failed (${response.status}): ${error}`);
  }

  const tokenData = (await response.json()) as { access_token: string };
  console.log("[OAuth] ✓ Access token:", tokenData.access_token.substring(0, 20) + "...");
  return tokenData.access_token;
}

/**
 * Create authenticated MCP client via pure HTTP OAuth flow
 *
 * @param credentials - User credentials (defaults to admin)
 * @returns Authenticated MCP client with cleanup function
 *
 * @example
 * const { client, cleanup } = await createAuthenticatedMCPClient();
 * try {
 *   const result = await client.callTool({ name: 'list_workflows', arguments: {} });
 *   // ... test assertions
 * } finally {
 *   await cleanup();
 * }
 *
 * @example
 * // Custom user
 * const { client } = await createAuthenticatedMCPClient({
 *   email: 'user@example.com',
 *   password: 'userpass'
 * });
 *
 * @example
 * // With email verification (for non-admin users)
 * const { client } = await createAuthenticatedMCPClient({
 *   email: 'newuser@example.com',
 *   password: 'userpass',
 *   verifyEmail: true
 * });
 */
export async function createAuthenticatedMCPClient(
  credentials: {
    email: string;
    password: string;
    verifyEmail?: boolean;
    adminCredentials?: { email: string; password: string };
  } = DEFAULT_ADMIN_CREDENTIALS,
): Promise<MCPTestClient> {
  const baseUrl = getTestBaseUrl();
  const fetchUrl = getTestFetchUrl();

  console.log("[mcp-auth] Starting OAuth flow...");
  console.log(`[mcp-auth] baseUrl=${baseUrl}, fetchUrl=${fetchUrl}`);

  // If email verification is requested, do it first via admin API
  if (credentials.verifyEmail && credentials.email !== DEFAULT_ADMIN_CREDENTIALS.email) {
    const adminCreds = credentials.adminCredentials || DEFAULT_ADMIN_CREDENTIALS;
    console.log("[mcp-auth] Email verification requested, signing in as admin first...");
    const adminSessionCookie = await signInUser(fetchUrl, adminCreds.email, adminCreds.password);
    await verifyUserEmailViaAdmin(fetchUrl, credentials.email, adminSessionCookie);
    console.log("[mcp-auth] ✓ Email verified for user");
  }

  // Step 1+2+3: Register client, sign in, get auth code (with retry on race conditions)
  let authCode: string;
  let clientData: { client_id: string; client_secret: string } | null = null;
  const maxOAuthAttempts = 3;
  for (let oauthAttempt = 1; oauthAttempt <= maxOAuthAttempts; oauthAttempt++) {
    try {
      // Register new client on first attempt or after invalid_client
      if (!clientData) {
        clientData = await registerOAuthClient(fetchUrl);
        console.log("[mcp-auth] ✓ OAuth client registered:", clientData.client_id);
      }
      const sessionCookie = await signInUser(fetchUrl, credentials.email, credentials.password);
      console.log("[mcp-auth] ✓ Signed in, got session cookie");
      authCode = await getAuthorizationCode(fetchUrl, clientData.client_id, sessionCookie);
      console.log("[mcp-auth] ✓ Got authorization code:", authCode.substring(0, 20) + "...");
      break;
    } catch (err) {
      if (oauthAttempt < maxOAuthAttempts) {
        if (err instanceof InvalidClientError) {
          // Client not visible in DB yet (WAL timing) — re-register with new client
          console.warn(`[mcp-auth] invalid_client (attempt ${oauthAttempt}), re-registering...`);
          clientData = null;
          await new Promise((r) => setTimeout(r, 1000 * oauthAttempt));
          continue;
        }
        if (String(err).includes("No authorization code")) {
          console.warn(
            `[mcp-auth] No auth code (attempt ${oauthAttempt}), retrying with fresh sign-in...`,
          );
          await new Promise((r) => setTimeout(r, 1000));
          continue;
        }
      }
      throw err;
    }
  }

  // Step 4: Exchange code for access token
  const accessToken = await exchangeCodeForToken(
    fetchUrl,
    authCode,
    clientData!.client_id,
    clientData!.client_secret,
  );
  console.log("[mcp-auth] ✓ Got access token:", accessToken.substring(0, 20) + "...");

  // Step 5: Connect MCP client with retry — SQLite WAL may delay session visibility
  const maxConnectRetries = 5;
  for (let attempt = 1; attempt <= maxConnectRetries; attempt++) {
    try {
      const mcpClient = new Client({ name: "test-client", version: "1.0.0" }, { capabilities: {} });
      const mcpTransport = new StreamableHTTPClientTransport(new URL(`${fetchUrl}/mcp`), {
        requestInit: {
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        },
      });

      console.log(
        `[OAuth] Step 5: Connecting MCP client (attempt ${attempt}/${maxConnectRetries})...`,
      );
      await mcpClient.connect(mcpTransport);
      console.log("[OAuth] ✓ MCP client connected");

      return {
        client: mcpClient,
        transport: mcpTransport,
        accessToken,
        cleanup: async () => {
          await mcpClient.close();
        },
      };
    } catch (err) {
      const errMsg = String(err);
      console.error(`[OAuth] MCP connect error (attempt ${attempt}): ${errMsg.substring(0, 200)}`);
      if (
        attempt < maxConnectRetries &&
        (errMsg.includes("401") || errMsg.includes("invalid_token"))
      ) {
        const delay = attempt * 300;
        console.warn(
          `[OAuth] MCP connect got 401 (session not yet visible), retrying in ${delay}ms...`,
        );
        await new Promise((r) => setTimeout(r, delay));
        continue;
      }
      throw err;
    }
  }
  throw new Error("Unreachable: MCP connect retries exhausted");
}

/**
 * Helper to call MCP tool and parse JSON result
 *
 * @param client - Authenticated MCP client
 * @param toolName - Name of the tool to call
 * @param args - Tool arguments
 * @returns Parsed JSON result from tool
 *
 * @example
 * const workflows = await callMCPTool(client, 'list_workflows', {});
 * expect(workflows).toHaveLength(23);
 *
 * @example
 * const settings = await callMCPTool(client, 'get_user_settings', { category: 'ui' });
 * expect(settings).toHaveProperty('ui.theme');
 */
export async function callMCPTool<T = any>(
  client: Client,
  toolName: string,
  args: Record<string, any> = {},
): Promise<T> {
  const result = await client.callTool({
    name: toolName,
    arguments: args,
  });

  if (!result.content || (result.content as any[]).length === 0) {
    throw new Error(`Tool ${toolName} returned no content`);
  }

  const content = (result.content as any[])[0];
  if (!("text" in content)) {
    throw new Error(`Tool ${toolName} returned non-text content`);
  }

  // Try to parse as JSON, if fails return raw text
  try {
    return JSON.parse(content.text) as T;
  } catch (e) {
    // Not JSON - return raw text
    return content.text as T;
  }
}

/**
 * Call MCP tool and return raw text response (for format verification)
 */
export async function callMCPToolRaw(
  client: Client,
  toolName: string,
  args: Record<string, any> = {},
): Promise<string> {
  const result = await client.callTool({
    name: toolName,
    arguments: args,
  });

  if (!result.content || (result.content as any[]).length === 0) {
    throw new Error(`Tool ${toolName} returned no content`);
  }

  const content = (result.content as any[])[0];
  if (!("text" in content)) {
    throw new Error(`Tool ${toolName} returned non-text content`);
  }

  return content.text;
}

/**
 * Parse token tool response (formatted text)
 * Extracts token, expires, and URL from formatted string
 */
export function parseTokenResponse(text: string): {
  token: string;
  expiresAt: string;
  uploadUrl?: string;
  downloadUrl?: string;
} {
  const lines = text.split("\n");
  const result: any = {};

  for (const line of lines) {
    const [key, ...valueParts] = line.split(":");
    const value = valueParts.join(":").trim();

    if (key.includes("Token")) {
      result.token = value;
    } else if (key.includes("Expires")) {
      result.expiresAt = value;
    } else if (key.includes("Upload URL")) {
      result.uploadUrl = value;
    } else if (key.includes("Download URL")) {
      result.downloadUrl = value;
    }
  }

  return result;
}
